//go:build s390x

package utf8

import "unicode/utf8"

// validBlocksVX runs the Lemire–Keiser SIMD validator over n full 16-byte vector
// blocks of src, returning 1 if those blocks contain no structural UTF-8 error
// within the processed range, 0 otherwise. It does not reject a sequence running
// past the last processed block; the caller re-validates the straddling rune and
// the tail with the scalar path. Generated by go-asmgen (utf8_s390x_gen.go), in
// utf8_s390x.s. The vector facility is baseline on z13+, so there is no runtime
// dispatch. s390x is big-endian; see the generator for lane order.
func validBlocksVX(src []byte, n int) uint8

// countContVX returns the number of UTF-8 continuation bytes ((b & 0xC0) ==
// 0x80) in the first n full 16-byte vector blocks of src. Generated by go-asmgen
// (utf8_s390x_gen.go), in utf8_s390x.s.
func countContVX(src []byte, n int) int64

// runeStart returns the largest index <= i in p that begins a rune (is not a
// continuation byte), scanning back at most 3 bytes; see utf8_amd64.go.
func runeStart(p []byte, i int) int {
	for j := 0; j < 3 && i > 0 && p[i-1]&0xC0 == 0x80; j++ {
		i--
	}
	if i > 0 {
		i--
	}
	return i
}

// valid validates the bulk of p with the vector kernel over the largest 16-byte
// block-aligned prefix, then re-validates from the last rune boundary before
// that split plus the tail with the standard library.
func valid(p []byte) bool {
	n := len(p)
	if n >= 16 {
		blocks := n / 16
		if validBlocksVX(p, blocks) == 0 {
			return false
		}
		return utf8.Valid(p[runeStart(p, blocks*16):])
	}
	return utf8.Valid(p)
}

// countValidPrefix returns RuneCount(p) given that p[:end] is valid UTF-8 and
// cont is the number of continuation bytes in p[:end]; see utf8_amd64.go.
func countValidPrefix(p []byte, end int, cont int64) int {
	split := runeStart(p, end)
	prefixRunes := (end - int(cont)) - 1
	return prefixRunes + utf8.RuneCount(p[split:])
}

// runeCount counts runes in p, byte-identically to unicode/utf8.RuneCount, using
// the vector continuation-byte counter over a SIMD-validated block-aligned
// prefix and the scalar decoder for the straddling rune, the tail, and any
// invalid input; see utf8_amd64.go for the full argument.
func runeCount(p []byte) int {
	n := len(p)
	if n >= 16 {
		blocks := n / 16
		if validBlocksVX(p, blocks) != 0 {
			return countValidPrefix(p, blocks*16, countContVX(p, blocks))
		}
	}
	return utf8.RuneCount(p)
}
