// Code generated by go-asmgen. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

TEXT ·validBlocksSSE(SB), NOSPLIT, $0-33
	MOVQ src_base+0(FP), SI
	MOVQ n+24(FP), CX
	PXOR X15, X15
	PXOR X13, X13
	PXOR X14, X14
	PXOR X12, X12
sloop:
	MOVOU (SI), X0
	MOVO X0, X1
	PSRLW $4, X1
	MOVOU c0F<>+0(SB), X2
	PAND X2, X1
	MOVO X0, X3
	MOVOU cF4<>+0(SB), X4
	PSUBUSB X4, X3
	POR X3, X15
	MOVOU contLen<>+0(SB), X2
	PSHUFB X1, X2
	MOVO X2, X3
	MOVO X12, X4
	PALIGNR $15, X4, X3
	PSUBUSB c01<>+0(SB), X3
	PADDB X2, X3
	MOVO X3, X5
	MOVO X12, X4
	PALIGNR $14, X4, X5
	PSUBUSB c02<>+0(SB), X5
	PADDB X5, X3
	MOVO X3, X5
	PCMPGTB X2, X5
	MOVO X2, X6
	MOVOU c00<>+0(SB), X7
	PCMPGTB X7, X6
	PCMPEQB X6, X5
	POR X5, X15
	MOVO X0, X8
	MOVO X13, X9
	PALIGNR $15, X9, X8
	MOVO X8, X9
	MOVOU cED<>+0(SB), X10
	PCMPEQB X10, X9
	MOVO X0, X10
	MOVOU c9F<>+0(SB), X11
	PCMPGTB X11, X10
	PAND X10, X9
	POR X9, X15
	MOVO X8, X9
	MOVOU cF4<>+0(SB), X10
	PCMPEQB X10, X9
	MOVO X0, X10
	MOVOU c8F<>+0(SB), X11
	PCMPGTB X11, X10
	PAND X10, X9
	POR X9, X15
	MOVO X1, X9
	MOVO X14, X10
	PALIGNR $15, X10, X9
	MOVOU initMins<>+0(SB), X10
	PSHUFB X9, X10
	PCMPGTB X8, X10
	MOVOU secMins<>+0(SB), X11
	PSHUFB X9, X11
	PCMPGTB X0, X11
	PAND X11, X10
	POR X10, X15
	MOVO X0, X13
	MOVO X1, X14
	MOVO X3, X12
	ADDQ $16, SI
	DECQ CX
	JNZ sloop
	XORQ AX, AX
	PTEST X15, X15
	SETEQ AX
	MOVB AX, ret+32(FP)
	RET

TEXT ·validBlocksAVX2(SB), NOSPLIT, $0-33
	MOVQ src_base+0(FP), SI
	MOVQ n+24(FP), CX
	VPXOR Y15, Y15, Y15
	VPXOR Y13, Y13, Y13
	VPXOR Y14, Y14, Y14
	VPXOR Y12, Y12, Y12
vloop:
	VMOVDQU (SI), Y0
	VPSRLW $4, Y0, Y1
	VPAND c0Fb<>+0(SB), Y1, Y1
	VPSUBUSB cF4b<>+0(SB), Y0, Y3
	VPOR Y3, Y15, Y15
	VMOVDQU contLenB<>+0(SB), Y2
	VPSHUFB Y1, Y2, Y2
	VPERM2I128 $0x21, Y2, Y12, Y4
	VPALIGNR $15, Y4, Y2, Y3
	VPSUBUSB c01b<>+0(SB), Y3, Y3
	VPADDB Y2, Y3, Y3
	VPERM2I128 $0x21, Y3, Y12, Y4
	VPALIGNR $14, Y4, Y3, Y5
	VPSUBUSB c02b<>+0(SB), Y5, Y5
	VPADDB Y5, Y3, Y3
	VPCMPGTB Y2, Y3, Y5
	VPCMPGTB c00b<>+0(SB), Y2, Y6
	VPCMPEQB Y6, Y5, Y5
	VPOR Y5, Y15, Y15
	VPERM2I128 $0x21, Y0, Y13, Y8
	VPALIGNR $15, Y8, Y0, Y8
	VPCMPEQB cEDb<>+0(SB), Y8, Y9
	VPCMPGTB c9Fb<>+0(SB), Y0, Y10
	VPAND Y10, Y9, Y9
	VPOR Y9, Y15, Y15
	VPCMPEQB cF4b<>+0(SB), Y8, Y9
	VPCMPGTB c8Fb<>+0(SB), Y0, Y10
	VPAND Y10, Y9, Y9
	VPOR Y9, Y15, Y15
	VPERM2I128 $0x21, Y1, Y14, Y9
	VPALIGNR $15, Y9, Y1, Y9
	VMOVDQU initMinsB<>+0(SB), Y10
	VPSHUFB Y9, Y10, Y10
	VPCMPGTB Y8, Y10, Y10
	VMOVDQU secMinsB<>+0(SB), Y11
	VPSHUFB Y9, Y11, Y11
	VPCMPGTB Y0, Y11, Y11
	VPAND Y11, Y10, Y10
	VPOR Y10, Y15, Y15
	VMOVDQA Y0, Y13
	VMOVDQA Y1, Y14
	VMOVDQA Y3, Y12
	ADDQ $32, SI
	DECQ CX
	JNZ vloop
	XORQ AX, AX
	VPTEST Y15, Y15
	SETEQ AX
	VZEROUPPER
	MOVB AX, ret+32(FP)
	RET

TEXT ·asciiBlocksSSE(SB), NOSPLIT, $0-40
	MOVQ src_base+0(FP), SI
	MOVQ n+24(FP), CX
	XORQ AX, AX
	MOVQ CX, R8
	SHRQ $2, R8
	TESTQ R8, R8
	JZ asse_tail
asse_loop4:
	MOVOU 0(SI), X0
	MOVOU 16(SI), X1
	MOVOU 32(SI), X2
	MOVOU 48(SI), X3
	POR X1, X0
	POR X3, X2
	POR X2, X0
	PMOVMSKB X0, DX
	TESTL DX, DX
	JNZ asse_back
	ADDQ $64, SI
	ADDQ $4, AX
	DECQ R8
	JNZ asse_loop4
	JMP asse_tail
asse_back:
asse_tail:
	MOVQ CX, R9
	SUBQ AX, R9
	TESTQ R9, R9
	JZ asse_done
asse_loop1:
	MOVOU (SI), X0
	PMOVMSKB X0, DX
	TESTL DX, DX
	JNZ asse_done
	ADDQ $16, SI
	INCQ AX
	DECQ R9
	JNZ asse_loop1
asse_done:
	MOVQ AX, ret+32(FP)
	RET

TEXT ·asciiBlocksAVX2(SB), NOSPLIT, $0-40
	MOVQ src_base+0(FP), SI
	MOVQ n+24(FP), CX
	XORQ AX, AX
	MOVQ CX, R8
	SHRQ $2, R8
	TESTQ R8, R8
	JZ aavx_tail
aavx_loop4:
	VMOVDQU 0(SI), Y0
	VMOVDQU 32(SI), Y1
	VMOVDQU 64(SI), Y2
	VMOVDQU 96(SI), Y3
	VPOR Y1, Y0, Y0
	VPOR Y3, Y2, Y2
	VPOR Y2, Y0, Y0
	VPMOVMSKB Y0, DX
	TESTL DX, DX
	JNZ aavx_back
	ADDQ $128, SI
	ADDQ $4, AX
	DECQ R8
	JNZ aavx_loop4
	JMP aavx_tail
aavx_back:
aavx_tail:
	MOVQ CX, R9
	SUBQ AX, R9
	TESTQ R9, R9
	JZ aavx_done
aavx_loop1:
	VMOVDQU (SI), Y0
	VPMOVMSKB Y0, DX
	TESTL DX, DX
	JNZ aavx_done
	ADDQ $32, SI
	INCQ AX
	DECQ R9
	JNZ aavx_loop1
aavx_done:
	VZEROUPPER
	MOVQ AX, ret+32(FP)
	RET

TEXT ·countContSSE(SB), NOSPLIT, $0-40
	MOVQ src_base+0(FP), SI
	MOVQ n+24(FP), CX
	XORQ AX, AX
	MOVOU cC0<>+0(SB), X1
	MOVOU c80<>+0(SB), X2
csloop:
	MOVOU (SI), X0
	PAND X1, X0
	PCMPEQB X2, X0
	PMOVMSKB X0, DX
	POPCNTL DX, DX
	ADDQ DX, AX
	ADDQ $16, SI
	DECQ CX
	JNZ csloop
	MOVQ AX, ret+32(FP)
	RET

TEXT ·countContAVX2(SB), NOSPLIT, $0-40
	MOVQ src_base+0(FP), SI
	MOVQ n+24(FP), CX
	XORQ AX, AX
	VMOVDQU cC0b<>+0(SB), Y1
	VMOVDQU c80b<>+0(SB), Y2
cvloop:
	VMOVDQU (SI), Y0
	VPAND Y1, Y0, Y0
	VPCMPEQB Y2, Y0, Y0
	VPMOVMSKB Y0, DX
	POPCNTL DX, DX
	ADDQ DX, AX
	ADDQ $32, SI
	DECQ CX
	JNZ cvloop
	VZEROUPPER
	MOVQ AX, ret+32(FP)
	RET

DATA contLen<>+0(SB)/1, $0x01
DATA contLen<>+1(SB)/1, $0x01
DATA contLen<>+2(SB)/1, $0x01
DATA contLen<>+3(SB)/1, $0x01
DATA contLen<>+4(SB)/1, $0x01
DATA contLen<>+5(SB)/1, $0x01
DATA contLen<>+6(SB)/1, $0x01
DATA contLen<>+7(SB)/1, $0x01
DATA contLen<>+8(SB)/1, $0x00
DATA contLen<>+9(SB)/1, $0x00
DATA contLen<>+10(SB)/1, $0x00
DATA contLen<>+11(SB)/1, $0x00
DATA contLen<>+12(SB)/1, $0x02
DATA contLen<>+13(SB)/1, $0x02
DATA contLen<>+14(SB)/1, $0x03
DATA contLen<>+15(SB)/1, $0x04
GLOBL contLen<>(SB), RODATA|NOPTR, $16

DATA initMins<>+0(SB)/1, $0x80
DATA initMins<>+1(SB)/1, $0x80
DATA initMins<>+2(SB)/1, $0x80
DATA initMins<>+3(SB)/1, $0x80
DATA initMins<>+4(SB)/1, $0x80
DATA initMins<>+5(SB)/1, $0x80
DATA initMins<>+6(SB)/1, $0x80
DATA initMins<>+7(SB)/1, $0x80
DATA initMins<>+8(SB)/1, $0x80
DATA initMins<>+9(SB)/1, $0x80
DATA initMins<>+10(SB)/1, $0x80
DATA initMins<>+11(SB)/1, $0x80
DATA initMins<>+12(SB)/1, $0xc2
DATA initMins<>+13(SB)/1, $0x80
DATA initMins<>+14(SB)/1, $0xe1
DATA initMins<>+15(SB)/1, $0xf1
GLOBL initMins<>(SB), RODATA|NOPTR, $16

DATA secMins<>+0(SB)/1, $0x80
DATA secMins<>+1(SB)/1, $0x80
DATA secMins<>+2(SB)/1, $0x80
DATA secMins<>+3(SB)/1, $0x80
DATA secMins<>+4(SB)/1, $0x80
DATA secMins<>+5(SB)/1, $0x80
DATA secMins<>+6(SB)/1, $0x80
DATA secMins<>+7(SB)/1, $0x80
DATA secMins<>+8(SB)/1, $0x80
DATA secMins<>+9(SB)/1, $0x80
DATA secMins<>+10(SB)/1, $0x80
DATA secMins<>+11(SB)/1, $0x80
DATA secMins<>+12(SB)/1, $0x7f
DATA secMins<>+13(SB)/1, $0x7f
DATA secMins<>+14(SB)/1, $0xa0
DATA secMins<>+15(SB)/1, $0x90
GLOBL secMins<>(SB), RODATA|NOPTR, $16

DATA c0F<>+0(SB)/1, $0x0f
DATA c0F<>+1(SB)/1, $0x0f
DATA c0F<>+2(SB)/1, $0x0f
DATA c0F<>+3(SB)/1, $0x0f
DATA c0F<>+4(SB)/1, $0x0f
DATA c0F<>+5(SB)/1, $0x0f
DATA c0F<>+6(SB)/1, $0x0f
DATA c0F<>+7(SB)/1, $0x0f
DATA c0F<>+8(SB)/1, $0x0f
DATA c0F<>+9(SB)/1, $0x0f
DATA c0F<>+10(SB)/1, $0x0f
DATA c0F<>+11(SB)/1, $0x0f
DATA c0F<>+12(SB)/1, $0x0f
DATA c0F<>+13(SB)/1, $0x0f
DATA c0F<>+14(SB)/1, $0x0f
DATA c0F<>+15(SB)/1, $0x0f
GLOBL c0F<>(SB), RODATA|NOPTR, $16

DATA c01<>+0(SB)/1, $0x01
DATA c01<>+1(SB)/1, $0x01
DATA c01<>+2(SB)/1, $0x01
DATA c01<>+3(SB)/1, $0x01
DATA c01<>+4(SB)/1, $0x01
DATA c01<>+5(SB)/1, $0x01
DATA c01<>+6(SB)/1, $0x01
DATA c01<>+7(SB)/1, $0x01
DATA c01<>+8(SB)/1, $0x01
DATA c01<>+9(SB)/1, $0x01
DATA c01<>+10(SB)/1, $0x01
DATA c01<>+11(SB)/1, $0x01
DATA c01<>+12(SB)/1, $0x01
DATA c01<>+13(SB)/1, $0x01
DATA c01<>+14(SB)/1, $0x01
DATA c01<>+15(SB)/1, $0x01
GLOBL c01<>(SB), RODATA|NOPTR, $16

DATA c02<>+0(SB)/1, $0x02
DATA c02<>+1(SB)/1, $0x02
DATA c02<>+2(SB)/1, $0x02
DATA c02<>+3(SB)/1, $0x02
DATA c02<>+4(SB)/1, $0x02
DATA c02<>+5(SB)/1, $0x02
DATA c02<>+6(SB)/1, $0x02
DATA c02<>+7(SB)/1, $0x02
DATA c02<>+8(SB)/1, $0x02
DATA c02<>+9(SB)/1, $0x02
DATA c02<>+10(SB)/1, $0x02
DATA c02<>+11(SB)/1, $0x02
DATA c02<>+12(SB)/1, $0x02
DATA c02<>+13(SB)/1, $0x02
DATA c02<>+14(SB)/1, $0x02
DATA c02<>+15(SB)/1, $0x02
GLOBL c02<>(SB), RODATA|NOPTR, $16

DATA cF4<>+0(SB)/1, $0xf4
DATA cF4<>+1(SB)/1, $0xf4
DATA cF4<>+2(SB)/1, $0xf4
DATA cF4<>+3(SB)/1, $0xf4
DATA cF4<>+4(SB)/1, $0xf4
DATA cF4<>+5(SB)/1, $0xf4
DATA cF4<>+6(SB)/1, $0xf4
DATA cF4<>+7(SB)/1, $0xf4
DATA cF4<>+8(SB)/1, $0xf4
DATA cF4<>+9(SB)/1, $0xf4
DATA cF4<>+10(SB)/1, $0xf4
DATA cF4<>+11(SB)/1, $0xf4
DATA cF4<>+12(SB)/1, $0xf4
DATA cF4<>+13(SB)/1, $0xf4
DATA cF4<>+14(SB)/1, $0xf4
DATA cF4<>+15(SB)/1, $0xf4
GLOBL cF4<>(SB), RODATA|NOPTR, $16

DATA cED<>+0(SB)/1, $0xed
DATA cED<>+1(SB)/1, $0xed
DATA cED<>+2(SB)/1, $0xed
DATA cED<>+3(SB)/1, $0xed
DATA cED<>+4(SB)/1, $0xed
DATA cED<>+5(SB)/1, $0xed
DATA cED<>+6(SB)/1, $0xed
DATA cED<>+7(SB)/1, $0xed
DATA cED<>+8(SB)/1, $0xed
DATA cED<>+9(SB)/1, $0xed
DATA cED<>+10(SB)/1, $0xed
DATA cED<>+11(SB)/1, $0xed
DATA cED<>+12(SB)/1, $0xed
DATA cED<>+13(SB)/1, $0xed
DATA cED<>+14(SB)/1, $0xed
DATA cED<>+15(SB)/1, $0xed
GLOBL cED<>(SB), RODATA|NOPTR, $16

DATA c9F<>+0(SB)/1, $0x9f
DATA c9F<>+1(SB)/1, $0x9f
DATA c9F<>+2(SB)/1, $0x9f
DATA c9F<>+3(SB)/1, $0x9f
DATA c9F<>+4(SB)/1, $0x9f
DATA c9F<>+5(SB)/1, $0x9f
DATA c9F<>+6(SB)/1, $0x9f
DATA c9F<>+7(SB)/1, $0x9f
DATA c9F<>+8(SB)/1, $0x9f
DATA c9F<>+9(SB)/1, $0x9f
DATA c9F<>+10(SB)/1, $0x9f
DATA c9F<>+11(SB)/1, $0x9f
DATA c9F<>+12(SB)/1, $0x9f
DATA c9F<>+13(SB)/1, $0x9f
DATA c9F<>+14(SB)/1, $0x9f
DATA c9F<>+15(SB)/1, $0x9f
GLOBL c9F<>(SB), RODATA|NOPTR, $16

DATA c8F<>+0(SB)/1, $0x8f
DATA c8F<>+1(SB)/1, $0x8f
DATA c8F<>+2(SB)/1, $0x8f
DATA c8F<>+3(SB)/1, $0x8f
DATA c8F<>+4(SB)/1, $0x8f
DATA c8F<>+5(SB)/1, $0x8f
DATA c8F<>+6(SB)/1, $0x8f
DATA c8F<>+7(SB)/1, $0x8f
DATA c8F<>+8(SB)/1, $0x8f
DATA c8F<>+9(SB)/1, $0x8f
DATA c8F<>+10(SB)/1, $0x8f
DATA c8F<>+11(SB)/1, $0x8f
DATA c8F<>+12(SB)/1, $0x8f
DATA c8F<>+13(SB)/1, $0x8f
DATA c8F<>+14(SB)/1, $0x8f
DATA c8F<>+15(SB)/1, $0x8f
GLOBL c8F<>(SB), RODATA|NOPTR, $16

DATA c00<>+0(SB)/1, $0x00
DATA c00<>+1(SB)/1, $0x00
DATA c00<>+2(SB)/1, $0x00
DATA c00<>+3(SB)/1, $0x00
DATA c00<>+4(SB)/1, $0x00
DATA c00<>+5(SB)/1, $0x00
DATA c00<>+6(SB)/1, $0x00
DATA c00<>+7(SB)/1, $0x00
DATA c00<>+8(SB)/1, $0x00
DATA c00<>+9(SB)/1, $0x00
DATA c00<>+10(SB)/1, $0x00
DATA c00<>+11(SB)/1, $0x00
DATA c00<>+12(SB)/1, $0x00
DATA c00<>+13(SB)/1, $0x00
DATA c00<>+14(SB)/1, $0x00
DATA c00<>+15(SB)/1, $0x00
GLOBL c00<>(SB), RODATA|NOPTR, $16

DATA contLenB<>+0(SB)/1, $0x01
DATA contLenB<>+1(SB)/1, $0x01
DATA contLenB<>+2(SB)/1, $0x01
DATA contLenB<>+3(SB)/1, $0x01
DATA contLenB<>+4(SB)/1, $0x01
DATA contLenB<>+5(SB)/1, $0x01
DATA contLenB<>+6(SB)/1, $0x01
DATA contLenB<>+7(SB)/1, $0x01
DATA contLenB<>+8(SB)/1, $0x00
DATA contLenB<>+9(SB)/1, $0x00
DATA contLenB<>+10(SB)/1, $0x00
DATA contLenB<>+11(SB)/1, $0x00
DATA contLenB<>+12(SB)/1, $0x02
DATA contLenB<>+13(SB)/1, $0x02
DATA contLenB<>+14(SB)/1, $0x03
DATA contLenB<>+15(SB)/1, $0x04
DATA contLenB<>+16(SB)/1, $0x01
DATA contLenB<>+17(SB)/1, $0x01
DATA contLenB<>+18(SB)/1, $0x01
DATA contLenB<>+19(SB)/1, $0x01
DATA contLenB<>+20(SB)/1, $0x01
DATA contLenB<>+21(SB)/1, $0x01
DATA contLenB<>+22(SB)/1, $0x01
DATA contLenB<>+23(SB)/1, $0x01
DATA contLenB<>+24(SB)/1, $0x00
DATA contLenB<>+25(SB)/1, $0x00
DATA contLenB<>+26(SB)/1, $0x00
DATA contLenB<>+27(SB)/1, $0x00
DATA contLenB<>+28(SB)/1, $0x02
DATA contLenB<>+29(SB)/1, $0x02
DATA contLenB<>+30(SB)/1, $0x03
DATA contLenB<>+31(SB)/1, $0x04
GLOBL contLenB<>(SB), RODATA|NOPTR, $32

DATA initMinsB<>+0(SB)/1, $0x80
DATA initMinsB<>+1(SB)/1, $0x80
DATA initMinsB<>+2(SB)/1, $0x80
DATA initMinsB<>+3(SB)/1, $0x80
DATA initMinsB<>+4(SB)/1, $0x80
DATA initMinsB<>+5(SB)/1, $0x80
DATA initMinsB<>+6(SB)/1, $0x80
DATA initMinsB<>+7(SB)/1, $0x80
DATA initMinsB<>+8(SB)/1, $0x80
DATA initMinsB<>+9(SB)/1, $0x80
DATA initMinsB<>+10(SB)/1, $0x80
DATA initMinsB<>+11(SB)/1, $0x80
DATA initMinsB<>+12(SB)/1, $0xc2
DATA initMinsB<>+13(SB)/1, $0x80
DATA initMinsB<>+14(SB)/1, $0xe1
DATA initMinsB<>+15(SB)/1, $0xf1
DATA initMinsB<>+16(SB)/1, $0x80
DATA initMinsB<>+17(SB)/1, $0x80
DATA initMinsB<>+18(SB)/1, $0x80
DATA initMinsB<>+19(SB)/1, $0x80
DATA initMinsB<>+20(SB)/1, $0x80
DATA initMinsB<>+21(SB)/1, $0x80
DATA initMinsB<>+22(SB)/1, $0x80
DATA initMinsB<>+23(SB)/1, $0x80
DATA initMinsB<>+24(SB)/1, $0x80
DATA initMinsB<>+25(SB)/1, $0x80
DATA initMinsB<>+26(SB)/1, $0x80
DATA initMinsB<>+27(SB)/1, $0x80
DATA initMinsB<>+28(SB)/1, $0xc2
DATA initMinsB<>+29(SB)/1, $0x80
DATA initMinsB<>+30(SB)/1, $0xe1
DATA initMinsB<>+31(SB)/1, $0xf1
GLOBL initMinsB<>(SB), RODATA|NOPTR, $32

DATA secMinsB<>+0(SB)/1, $0x80
DATA secMinsB<>+1(SB)/1, $0x80
DATA secMinsB<>+2(SB)/1, $0x80
DATA secMinsB<>+3(SB)/1, $0x80
DATA secMinsB<>+4(SB)/1, $0x80
DATA secMinsB<>+5(SB)/1, $0x80
DATA secMinsB<>+6(SB)/1, $0x80
DATA secMinsB<>+7(SB)/1, $0x80
DATA secMinsB<>+8(SB)/1, $0x80
DATA secMinsB<>+9(SB)/1, $0x80
DATA secMinsB<>+10(SB)/1, $0x80
DATA secMinsB<>+11(SB)/1, $0x80
DATA secMinsB<>+12(SB)/1, $0x7f
DATA secMinsB<>+13(SB)/1, $0x7f
DATA secMinsB<>+14(SB)/1, $0xa0
DATA secMinsB<>+15(SB)/1, $0x90
DATA secMinsB<>+16(SB)/1, $0x80
DATA secMinsB<>+17(SB)/1, $0x80
DATA secMinsB<>+18(SB)/1, $0x80
DATA secMinsB<>+19(SB)/1, $0x80
DATA secMinsB<>+20(SB)/1, $0x80
DATA secMinsB<>+21(SB)/1, $0x80
DATA secMinsB<>+22(SB)/1, $0x80
DATA secMinsB<>+23(SB)/1, $0x80
DATA secMinsB<>+24(SB)/1, $0x80
DATA secMinsB<>+25(SB)/1, $0x80
DATA secMinsB<>+26(SB)/1, $0x80
DATA secMinsB<>+27(SB)/1, $0x80
DATA secMinsB<>+28(SB)/1, $0x7f
DATA secMinsB<>+29(SB)/1, $0x7f
DATA secMinsB<>+30(SB)/1, $0xa0
DATA secMinsB<>+31(SB)/1, $0x90
GLOBL secMinsB<>(SB), RODATA|NOPTR, $32

DATA c0Fb<>+0(SB)/1, $0x0f
DATA c0Fb<>+1(SB)/1, $0x0f
DATA c0Fb<>+2(SB)/1, $0x0f
DATA c0Fb<>+3(SB)/1, $0x0f
DATA c0Fb<>+4(SB)/1, $0x0f
DATA c0Fb<>+5(SB)/1, $0x0f
DATA c0Fb<>+6(SB)/1, $0x0f
DATA c0Fb<>+7(SB)/1, $0x0f
DATA c0Fb<>+8(SB)/1, $0x0f
DATA c0Fb<>+9(SB)/1, $0x0f
DATA c0Fb<>+10(SB)/1, $0x0f
DATA c0Fb<>+11(SB)/1, $0x0f
DATA c0Fb<>+12(SB)/1, $0x0f
DATA c0Fb<>+13(SB)/1, $0x0f
DATA c0Fb<>+14(SB)/1, $0x0f
DATA c0Fb<>+15(SB)/1, $0x0f
DATA c0Fb<>+16(SB)/1, $0x0f
DATA c0Fb<>+17(SB)/1, $0x0f
DATA c0Fb<>+18(SB)/1, $0x0f
DATA c0Fb<>+19(SB)/1, $0x0f
DATA c0Fb<>+20(SB)/1, $0x0f
DATA c0Fb<>+21(SB)/1, $0x0f
DATA c0Fb<>+22(SB)/1, $0x0f
DATA c0Fb<>+23(SB)/1, $0x0f
DATA c0Fb<>+24(SB)/1, $0x0f
DATA c0Fb<>+25(SB)/1, $0x0f
DATA c0Fb<>+26(SB)/1, $0x0f
DATA c0Fb<>+27(SB)/1, $0x0f
DATA c0Fb<>+28(SB)/1, $0x0f
DATA c0Fb<>+29(SB)/1, $0x0f
DATA c0Fb<>+30(SB)/1, $0x0f
DATA c0Fb<>+31(SB)/1, $0x0f
GLOBL c0Fb<>(SB), RODATA|NOPTR, $32

DATA c01b<>+0(SB)/1, $0x01
DATA c01b<>+1(SB)/1, $0x01
DATA c01b<>+2(SB)/1, $0x01
DATA c01b<>+3(SB)/1, $0x01
DATA c01b<>+4(SB)/1, $0x01
DATA c01b<>+5(SB)/1, $0x01
DATA c01b<>+6(SB)/1, $0x01
DATA c01b<>+7(SB)/1, $0x01
DATA c01b<>+8(SB)/1, $0x01
DATA c01b<>+9(SB)/1, $0x01
DATA c01b<>+10(SB)/1, $0x01
DATA c01b<>+11(SB)/1, $0x01
DATA c01b<>+12(SB)/1, $0x01
DATA c01b<>+13(SB)/1, $0x01
DATA c01b<>+14(SB)/1, $0x01
DATA c01b<>+15(SB)/1, $0x01
DATA c01b<>+16(SB)/1, $0x01
DATA c01b<>+17(SB)/1, $0x01
DATA c01b<>+18(SB)/1, $0x01
DATA c01b<>+19(SB)/1, $0x01
DATA c01b<>+20(SB)/1, $0x01
DATA c01b<>+21(SB)/1, $0x01
DATA c01b<>+22(SB)/1, $0x01
DATA c01b<>+23(SB)/1, $0x01
DATA c01b<>+24(SB)/1, $0x01
DATA c01b<>+25(SB)/1, $0x01
DATA c01b<>+26(SB)/1, $0x01
DATA c01b<>+27(SB)/1, $0x01
DATA c01b<>+28(SB)/1, $0x01
DATA c01b<>+29(SB)/1, $0x01
DATA c01b<>+30(SB)/1, $0x01
DATA c01b<>+31(SB)/1, $0x01
GLOBL c01b<>(SB), RODATA|NOPTR, $32

DATA c02b<>+0(SB)/1, $0x02
DATA c02b<>+1(SB)/1, $0x02
DATA c02b<>+2(SB)/1, $0x02
DATA c02b<>+3(SB)/1, $0x02
DATA c02b<>+4(SB)/1, $0x02
DATA c02b<>+5(SB)/1, $0x02
DATA c02b<>+6(SB)/1, $0x02
DATA c02b<>+7(SB)/1, $0x02
DATA c02b<>+8(SB)/1, $0x02
DATA c02b<>+9(SB)/1, $0x02
DATA c02b<>+10(SB)/1, $0x02
DATA c02b<>+11(SB)/1, $0x02
DATA c02b<>+12(SB)/1, $0x02
DATA c02b<>+13(SB)/1, $0x02
DATA c02b<>+14(SB)/1, $0x02
DATA c02b<>+15(SB)/1, $0x02
DATA c02b<>+16(SB)/1, $0x02
DATA c02b<>+17(SB)/1, $0x02
DATA c02b<>+18(SB)/1, $0x02
DATA c02b<>+19(SB)/1, $0x02
DATA c02b<>+20(SB)/1, $0x02
DATA c02b<>+21(SB)/1, $0x02
DATA c02b<>+22(SB)/1, $0x02
DATA c02b<>+23(SB)/1, $0x02
DATA c02b<>+24(SB)/1, $0x02
DATA c02b<>+25(SB)/1, $0x02
DATA c02b<>+26(SB)/1, $0x02
DATA c02b<>+27(SB)/1, $0x02
DATA c02b<>+28(SB)/1, $0x02
DATA c02b<>+29(SB)/1, $0x02
DATA c02b<>+30(SB)/1, $0x02
DATA c02b<>+31(SB)/1, $0x02
GLOBL c02b<>(SB), RODATA|NOPTR, $32

DATA cF4b<>+0(SB)/1, $0xf4
DATA cF4b<>+1(SB)/1, $0xf4
DATA cF4b<>+2(SB)/1, $0xf4
DATA cF4b<>+3(SB)/1, $0xf4
DATA cF4b<>+4(SB)/1, $0xf4
DATA cF4b<>+5(SB)/1, $0xf4
DATA cF4b<>+6(SB)/1, $0xf4
DATA cF4b<>+7(SB)/1, $0xf4
DATA cF4b<>+8(SB)/1, $0xf4
DATA cF4b<>+9(SB)/1, $0xf4
DATA cF4b<>+10(SB)/1, $0xf4
DATA cF4b<>+11(SB)/1, $0xf4
DATA cF4b<>+12(SB)/1, $0xf4
DATA cF4b<>+13(SB)/1, $0xf4
DATA cF4b<>+14(SB)/1, $0xf4
DATA cF4b<>+15(SB)/1, $0xf4
DATA cF4b<>+16(SB)/1, $0xf4
DATA cF4b<>+17(SB)/1, $0xf4
DATA cF4b<>+18(SB)/1, $0xf4
DATA cF4b<>+19(SB)/1, $0xf4
DATA cF4b<>+20(SB)/1, $0xf4
DATA cF4b<>+21(SB)/1, $0xf4
DATA cF4b<>+22(SB)/1, $0xf4
DATA cF4b<>+23(SB)/1, $0xf4
DATA cF4b<>+24(SB)/1, $0xf4
DATA cF4b<>+25(SB)/1, $0xf4
DATA cF4b<>+26(SB)/1, $0xf4
DATA cF4b<>+27(SB)/1, $0xf4
DATA cF4b<>+28(SB)/1, $0xf4
DATA cF4b<>+29(SB)/1, $0xf4
DATA cF4b<>+30(SB)/1, $0xf4
DATA cF4b<>+31(SB)/1, $0xf4
GLOBL cF4b<>(SB), RODATA|NOPTR, $32

DATA cEDb<>+0(SB)/1, $0xed
DATA cEDb<>+1(SB)/1, $0xed
DATA cEDb<>+2(SB)/1, $0xed
DATA cEDb<>+3(SB)/1, $0xed
DATA cEDb<>+4(SB)/1, $0xed
DATA cEDb<>+5(SB)/1, $0xed
DATA cEDb<>+6(SB)/1, $0xed
DATA cEDb<>+7(SB)/1, $0xed
DATA cEDb<>+8(SB)/1, $0xed
DATA cEDb<>+9(SB)/1, $0xed
DATA cEDb<>+10(SB)/1, $0xed
DATA cEDb<>+11(SB)/1, $0xed
DATA cEDb<>+12(SB)/1, $0xed
DATA cEDb<>+13(SB)/1, $0xed
DATA cEDb<>+14(SB)/1, $0xed
DATA cEDb<>+15(SB)/1, $0xed
DATA cEDb<>+16(SB)/1, $0xed
DATA cEDb<>+17(SB)/1, $0xed
DATA cEDb<>+18(SB)/1, $0xed
DATA cEDb<>+19(SB)/1, $0xed
DATA cEDb<>+20(SB)/1, $0xed
DATA cEDb<>+21(SB)/1, $0xed
DATA cEDb<>+22(SB)/1, $0xed
DATA cEDb<>+23(SB)/1, $0xed
DATA cEDb<>+24(SB)/1, $0xed
DATA cEDb<>+25(SB)/1, $0xed
DATA cEDb<>+26(SB)/1, $0xed
DATA cEDb<>+27(SB)/1, $0xed
DATA cEDb<>+28(SB)/1, $0xed
DATA cEDb<>+29(SB)/1, $0xed
DATA cEDb<>+30(SB)/1, $0xed
DATA cEDb<>+31(SB)/1, $0xed
GLOBL cEDb<>(SB), RODATA|NOPTR, $32

DATA c9Fb<>+0(SB)/1, $0x9f
DATA c9Fb<>+1(SB)/1, $0x9f
DATA c9Fb<>+2(SB)/1, $0x9f
DATA c9Fb<>+3(SB)/1, $0x9f
DATA c9Fb<>+4(SB)/1, $0x9f
DATA c9Fb<>+5(SB)/1, $0x9f
DATA c9Fb<>+6(SB)/1, $0x9f
DATA c9Fb<>+7(SB)/1, $0x9f
DATA c9Fb<>+8(SB)/1, $0x9f
DATA c9Fb<>+9(SB)/1, $0x9f
DATA c9Fb<>+10(SB)/1, $0x9f
DATA c9Fb<>+11(SB)/1, $0x9f
DATA c9Fb<>+12(SB)/1, $0x9f
DATA c9Fb<>+13(SB)/1, $0x9f
DATA c9Fb<>+14(SB)/1, $0x9f
DATA c9Fb<>+15(SB)/1, $0x9f
DATA c9Fb<>+16(SB)/1, $0x9f
DATA c9Fb<>+17(SB)/1, $0x9f
DATA c9Fb<>+18(SB)/1, $0x9f
DATA c9Fb<>+19(SB)/1, $0x9f
DATA c9Fb<>+20(SB)/1, $0x9f
DATA c9Fb<>+21(SB)/1, $0x9f
DATA c9Fb<>+22(SB)/1, $0x9f
DATA c9Fb<>+23(SB)/1, $0x9f
DATA c9Fb<>+24(SB)/1, $0x9f
DATA c9Fb<>+25(SB)/1, $0x9f
DATA c9Fb<>+26(SB)/1, $0x9f
DATA c9Fb<>+27(SB)/1, $0x9f
DATA c9Fb<>+28(SB)/1, $0x9f
DATA c9Fb<>+29(SB)/1, $0x9f
DATA c9Fb<>+30(SB)/1, $0x9f
DATA c9Fb<>+31(SB)/1, $0x9f
GLOBL c9Fb<>(SB), RODATA|NOPTR, $32

DATA c8Fb<>+0(SB)/1, $0x8f
DATA c8Fb<>+1(SB)/1, $0x8f
DATA c8Fb<>+2(SB)/1, $0x8f
DATA c8Fb<>+3(SB)/1, $0x8f
DATA c8Fb<>+4(SB)/1, $0x8f
DATA c8Fb<>+5(SB)/1, $0x8f
DATA c8Fb<>+6(SB)/1, $0x8f
DATA c8Fb<>+7(SB)/1, $0x8f
DATA c8Fb<>+8(SB)/1, $0x8f
DATA c8Fb<>+9(SB)/1, $0x8f
DATA c8Fb<>+10(SB)/1, $0x8f
DATA c8Fb<>+11(SB)/1, $0x8f
DATA c8Fb<>+12(SB)/1, $0x8f
DATA c8Fb<>+13(SB)/1, $0x8f
DATA c8Fb<>+14(SB)/1, $0x8f
DATA c8Fb<>+15(SB)/1, $0x8f
DATA c8Fb<>+16(SB)/1, $0x8f
DATA c8Fb<>+17(SB)/1, $0x8f
DATA c8Fb<>+18(SB)/1, $0x8f
DATA c8Fb<>+19(SB)/1, $0x8f
DATA c8Fb<>+20(SB)/1, $0x8f
DATA c8Fb<>+21(SB)/1, $0x8f
DATA c8Fb<>+22(SB)/1, $0x8f
DATA c8Fb<>+23(SB)/1, $0x8f
DATA c8Fb<>+24(SB)/1, $0x8f
DATA c8Fb<>+25(SB)/1, $0x8f
DATA c8Fb<>+26(SB)/1, $0x8f
DATA c8Fb<>+27(SB)/1, $0x8f
DATA c8Fb<>+28(SB)/1, $0x8f
DATA c8Fb<>+29(SB)/1, $0x8f
DATA c8Fb<>+30(SB)/1, $0x8f
DATA c8Fb<>+31(SB)/1, $0x8f
GLOBL c8Fb<>(SB), RODATA|NOPTR, $32

DATA c00b<>+0(SB)/1, $0x00
DATA c00b<>+1(SB)/1, $0x00
DATA c00b<>+2(SB)/1, $0x00
DATA c00b<>+3(SB)/1, $0x00
DATA c00b<>+4(SB)/1, $0x00
DATA c00b<>+5(SB)/1, $0x00
DATA c00b<>+6(SB)/1, $0x00
DATA c00b<>+7(SB)/1, $0x00
DATA c00b<>+8(SB)/1, $0x00
DATA c00b<>+9(SB)/1, $0x00
DATA c00b<>+10(SB)/1, $0x00
DATA c00b<>+11(SB)/1, $0x00
DATA c00b<>+12(SB)/1, $0x00
DATA c00b<>+13(SB)/1, $0x00
DATA c00b<>+14(SB)/1, $0x00
DATA c00b<>+15(SB)/1, $0x00
DATA c00b<>+16(SB)/1, $0x00
DATA c00b<>+17(SB)/1, $0x00
DATA c00b<>+18(SB)/1, $0x00
DATA c00b<>+19(SB)/1, $0x00
DATA c00b<>+20(SB)/1, $0x00
DATA c00b<>+21(SB)/1, $0x00
DATA c00b<>+22(SB)/1, $0x00
DATA c00b<>+23(SB)/1, $0x00
DATA c00b<>+24(SB)/1, $0x00
DATA c00b<>+25(SB)/1, $0x00
DATA c00b<>+26(SB)/1, $0x00
DATA c00b<>+27(SB)/1, $0x00
DATA c00b<>+28(SB)/1, $0x00
DATA c00b<>+29(SB)/1, $0x00
DATA c00b<>+30(SB)/1, $0x00
DATA c00b<>+31(SB)/1, $0x00
GLOBL c00b<>(SB), RODATA|NOPTR, $32

DATA cC0<>+0(SB)/1, $0xc0
DATA cC0<>+1(SB)/1, $0xc0
DATA cC0<>+2(SB)/1, $0xc0
DATA cC0<>+3(SB)/1, $0xc0
DATA cC0<>+4(SB)/1, $0xc0
DATA cC0<>+5(SB)/1, $0xc0
DATA cC0<>+6(SB)/1, $0xc0
DATA cC0<>+7(SB)/1, $0xc0
DATA cC0<>+8(SB)/1, $0xc0
DATA cC0<>+9(SB)/1, $0xc0
DATA cC0<>+10(SB)/1, $0xc0
DATA cC0<>+11(SB)/1, $0xc0
DATA cC0<>+12(SB)/1, $0xc0
DATA cC0<>+13(SB)/1, $0xc0
DATA cC0<>+14(SB)/1, $0xc0
DATA cC0<>+15(SB)/1, $0xc0
GLOBL cC0<>(SB), RODATA|NOPTR, $16

DATA c80<>+0(SB)/1, $0x80
DATA c80<>+1(SB)/1, $0x80
DATA c80<>+2(SB)/1, $0x80
DATA c80<>+3(SB)/1, $0x80
DATA c80<>+4(SB)/1, $0x80
DATA c80<>+5(SB)/1, $0x80
DATA c80<>+6(SB)/1, $0x80
DATA c80<>+7(SB)/1, $0x80
DATA c80<>+8(SB)/1, $0x80
DATA c80<>+9(SB)/1, $0x80
DATA c80<>+10(SB)/1, $0x80
DATA c80<>+11(SB)/1, $0x80
DATA c80<>+12(SB)/1, $0x80
DATA c80<>+13(SB)/1, $0x80
DATA c80<>+14(SB)/1, $0x80
DATA c80<>+15(SB)/1, $0x80
GLOBL c80<>(SB), RODATA|NOPTR, $16

DATA cC0b<>+0(SB)/1, $0xc0
DATA cC0b<>+1(SB)/1, $0xc0
DATA cC0b<>+2(SB)/1, $0xc0
DATA cC0b<>+3(SB)/1, $0xc0
DATA cC0b<>+4(SB)/1, $0xc0
DATA cC0b<>+5(SB)/1, $0xc0
DATA cC0b<>+6(SB)/1, $0xc0
DATA cC0b<>+7(SB)/1, $0xc0
DATA cC0b<>+8(SB)/1, $0xc0
DATA cC0b<>+9(SB)/1, $0xc0
DATA cC0b<>+10(SB)/1, $0xc0
DATA cC0b<>+11(SB)/1, $0xc0
DATA cC0b<>+12(SB)/1, $0xc0
DATA cC0b<>+13(SB)/1, $0xc0
DATA cC0b<>+14(SB)/1, $0xc0
DATA cC0b<>+15(SB)/1, $0xc0
DATA cC0b<>+16(SB)/1, $0xc0
DATA cC0b<>+17(SB)/1, $0xc0
DATA cC0b<>+18(SB)/1, $0xc0
DATA cC0b<>+19(SB)/1, $0xc0
DATA cC0b<>+20(SB)/1, $0xc0
DATA cC0b<>+21(SB)/1, $0xc0
DATA cC0b<>+22(SB)/1, $0xc0
DATA cC0b<>+23(SB)/1, $0xc0
DATA cC0b<>+24(SB)/1, $0xc0
DATA cC0b<>+25(SB)/1, $0xc0
DATA cC0b<>+26(SB)/1, $0xc0
DATA cC0b<>+27(SB)/1, $0xc0
DATA cC0b<>+28(SB)/1, $0xc0
DATA cC0b<>+29(SB)/1, $0xc0
DATA cC0b<>+30(SB)/1, $0xc0
DATA cC0b<>+31(SB)/1, $0xc0
GLOBL cC0b<>(SB), RODATA|NOPTR, $32

DATA c80b<>+0(SB)/1, $0x80
DATA c80b<>+1(SB)/1, $0x80
DATA c80b<>+2(SB)/1, $0x80
DATA c80b<>+3(SB)/1, $0x80
DATA c80b<>+4(SB)/1, $0x80
DATA c80b<>+5(SB)/1, $0x80
DATA c80b<>+6(SB)/1, $0x80
DATA c80b<>+7(SB)/1, $0x80
DATA c80b<>+8(SB)/1, $0x80
DATA c80b<>+9(SB)/1, $0x80
DATA c80b<>+10(SB)/1, $0x80
DATA c80b<>+11(SB)/1, $0x80
DATA c80b<>+12(SB)/1, $0x80
DATA c80b<>+13(SB)/1, $0x80
DATA c80b<>+14(SB)/1, $0x80
DATA c80b<>+15(SB)/1, $0x80
DATA c80b<>+16(SB)/1, $0x80
DATA c80b<>+17(SB)/1, $0x80
DATA c80b<>+18(SB)/1, $0x80
DATA c80b<>+19(SB)/1, $0x80
DATA c80b<>+20(SB)/1, $0x80
DATA c80b<>+21(SB)/1, $0x80
DATA c80b<>+22(SB)/1, $0x80
DATA c80b<>+23(SB)/1, $0x80
DATA c80b<>+24(SB)/1, $0x80
DATA c80b<>+25(SB)/1, $0x80
DATA c80b<>+26(SB)/1, $0x80
DATA c80b<>+27(SB)/1, $0x80
DATA c80b<>+28(SB)/1, $0x80
DATA c80b<>+29(SB)/1, $0x80
DATA c80b<>+30(SB)/1, $0x80
DATA c80b<>+31(SB)/1, $0x80
GLOBL c80b<>(SB), RODATA|NOPTR, $32

