// Package utf8 is a drop-in fast path for UTF-8 validation and rune counting.
// The bulk of the work runs a SIMD kernel generated by go-asmgen (amd64
// SSE/SSSE3 and AVX2 today; other arches fall back to the standard library):
// Valid implements the Lemire–Keiser "Validating UTF-8 In Less Than One
// Instruction Per Byte" lookup-based algorithm, and RuneCount counts
// non-continuation bytes over a SIMD-validated prefix. Results are
// byte-identical to unicode/utf8.Valid and unicode/utf8.RuneCount on all input.
package utf8

import "unicode/utf8"

// Valid reports whether p consists entirely of valid UTF-8-encoded runes. It is
// a drop-in replacement for unicode/utf8.Valid and returns the same result for
// every input.
func Valid(p []byte) bool {
	return valid(p)
}

// ValidString reports whether s consists entirely of valid UTF-8-encoded runes.
// It is a drop-in replacement for unicode/utf8.ValidString.
func ValidString(s string) bool {
	// utf8.ValidString shares the scalar path; the SIMD kernel works on []byte.
	// For strings we defer to the stdlib, which is already well optimised for the
	// string case and keeps the API allocation-free.
	return utf8.ValidString(s)
}

// RuneCount returns the number of runes in p. It is a drop-in replacement for
// unicode/utf8.RuneCount and returns the same count for every input, including
// erroneous and short encodings (each treated as a single 1-byte rune). The
// bulk of the count runs a SIMD kernel; see runeCount for the algorithm.
func RuneCount(p []byte) int {
	return runeCount(p)
}

// RuneCountInString is like RuneCount but its input is a string. It is a
// drop-in replacement for unicode/utf8.RuneCountInString.
func RuneCountInString(s string) int {
	// The SIMD kernel works on []byte. Converting s would allocate and copy,
	// which would dwarf the kernel's saving for the common short-string case, so
	// defer to the stdlib, which is already well optimised for strings.
	return utf8.RuneCountInString(s)
}
