// Package utf8 is a drop-in fast path for UTF-8 validation. The bulk of the
// check runs a SIMD kernel generated by go-asmgen (amd64 SSE/SSSE3 and AVX2
// today; other arches fall back to the standard library), implementing the
// Lemire–Keiser "Validating UTF-8 In Less Than One Instruction Per Byte"
// lookup-based algorithm. Results are byte-identical to unicode/utf8.Valid.
package utf8

import "unicode/utf8"

// Valid reports whether p consists entirely of valid UTF-8-encoded runes. It is
// a drop-in replacement for unicode/utf8.Valid and returns the same result for
// every input.
func Valid(p []byte) bool {
	return valid(p)
}

// ValidString reports whether s consists entirely of valid UTF-8-encoded runes.
// It is a drop-in replacement for unicode/utf8.ValidString.
func ValidString(s string) bool {
	// utf8.ValidString shares the scalar path; the SIMD kernel works on []byte.
	// For strings we defer to the stdlib, which is already well optimised for the
	// string case and keeps the API allocation-free.
	return utf8.ValidString(s)
}
