//go:build arm64

package utf8

import "unicode/utf8"

// validBlocks runs the Lemire–Keiser NEON validator over n full 16-byte blocks
// of src and returns 1 if those blocks contain no structural UTF-8 error (bad
// continuation, overlong, surrogate, too-large) within the processed range, 0
// otherwise. It does not reject a sequence that runs past the last processed
// block; the caller re-validates that straddling rune and the tail with the
// scalar path. Generated by go-asmgen (utf8_arm64_gen.go), in utf8_arm64.s.
func validBlocks(src []byte, n int) uint8

// countCont returns the number of UTF-8 continuation bytes (those with
// (b & 0xC0) == 0x80) in the first n 16-byte blocks of src. The non-continuation
// count — i.e. the rune count of valid UTF-8 — is n*16 minus this. Generated by
// go-asmgen (utf8_arm64_gen.go), in utf8_arm64.s.
func countCont(src []byte, n int) int64

// asciiBlocks returns the number of leading 16-byte blocks of src (out of n)
// that are pure ASCII (every byte < 0x80), stopping at the first block with a
// high bit. A pure-ASCII run costs a load + a high-bit test per block, so this
// is the memory-bound fast path that keeps all-ASCII input from regressing
// against the stdlib word-at-a-time scan when the heavy Lemire–Keiser validator
// would otherwise touch every byte. Generated by go-asmgen (utf8_arm64_gen.go),
// in utf8_arm64.s.
func asciiBlocks(src []byte, n int) int64

// runeStart returns the largest index <= i in p that begins a rune (i.e. is not
// a UTF-8 continuation byte), scanning back at most 3 bytes. A rune is at most 4
// bytes, so a boundary always exists within that window unless p[i-3:i] are all
// continuations (a malformed run), in which case we fall back to i so the
// scalar path sees and rejects it.
func runeStart(p []byte, i int) int {
	for j := 0; j < 3 && i > 0 && p[i-1]&0xC0 == 0x80; j++ {
		i--
	}
	if i > 0 {
		i--
	}
	return i
}

// valid validates the bulk of p with the NEON kernel over the largest
// 16-byte-aligned prefix, then re-validates from the last rune boundary before
// that split (so a rune straddling the boundary is checked in full) plus the
// tail with the standard library.
func valid(p []byte) bool {
	n := len(p)
	if n >= 16 {
		blocks := n / 16
		// Cheap ASCII pre-scan: pure-ASCII bytes are trivially valid, so if the
		// whole block-aligned region is ASCII only the sub-16 tail remains.
		if ab := int(asciiBlocks(p, blocks)); ab == blocks {
			return utf8.Valid(p[blocks*16:])
		}
		if validBlocks(p, blocks) == 0 {
			return false
		}
		return utf8.Valid(p[runeStart(p, blocks*16):])
	}
	return utf8.Valid(p)
}

// runeCount counts the runes in p, byte-identically to unicode/utf8.RuneCount.
// In valid UTF-8 the rune count equals the number of non-continuation bytes;
// that identity only holds over a prefix the validator confirms is valid UTF-8
// ending on a rune boundary, so the straddling rune and the tail go to the
// scalar decoder, and invalid input falls back to the scalar decoder entirely.
func runeCount(p []byte) int {
	n := len(p)
	if n >= 16 {
		blocks := n / 16
		// Cheap ASCII pre-scan: a pure-ASCII prefix has one rune per byte, so if
		// the whole block-aligned region is ASCII the count is blocks*16 plus the
		// scalar count of the sub-16 tail — no heavy validator pass needed.
		if ab := int(asciiBlocks(p, blocks)); ab == blocks {
			return blocks*16 + utf8.RuneCount(p[blocks*16:])
		}
		if validBlocks(p, blocks) != 0 {
			return countValidPrefix(p, blocks*16, countCont(p, blocks))
		}
		return utf8.RuneCount(p)
	}
	return utf8.RuneCount(p)
}

// countValidPrefix returns RuneCount(p) given that p[:end] is valid UTF-8 and
// cont is the number of continuation bytes in p[:end]. It splits at the rune
// boundary at or before end (runeStart) so the straddling rune is decoded once,
// by the scalar tail, and never double-counted.
func countValidPrefix(p []byte, end int, cont int64) int {
	split := runeStart(p, end)
	prefixRunes := (end - int(cont)) - 1
	return prefixRunes + utf8.RuneCount(p[split:])
}
