// Code generated by go-asmgen. DO NOT EDIT.

//go:build s390x

#include "textflag.h"

TEXT ·validBlocksVX(SB), NOSPLIT, $0-33
	MOVD src_base+0(FP), R2
	MOVD n+24(FP), R3
	MOVD $contLen_z<>+0(SB), R5
	VL (R5), V24
	MOVD $initMins_z<>+0(SB), R5
	VL (R5), V25
	MOVD $secMins_z<>+0(SB), R5
	VL (R5), V26
	MOVD $cF4_z<>+0(SB), R5
	VL (R5), V27
	MOVD $c01_z<>+0(SB), R5
	VL (R5), V28
	MOVD $c02_z<>+0(SB), R5
	VL (R5), V29
	VZERO V30
	VZERO V20
	VZERO V21
	VZERO V22
	VZERO V23
sloop:
	VL (R2), V0
	VESRLB $4, V0, V1
	VMNLB V0, V27, V3
	VSB V3, V0, V3
	VO V3, V20, V20
	VPERM V24, V24, V1, V2
	VSLDB $15, V23, V2, V3
	VMNLB V3, V28, V4
	VSB V4, V3, V3
	VAB V2, V3, V3
	VSLDB $14, V23, V3, V5
	VMNLB V5, V29, V4
	VSB V4, V5, V5
	VAB V5, V3, V3
	VCHB V3, V2, V5
	VCHB V2, V30, V6
	VCEQB V6, V5, V5
	VO V5, V20, V20
	VSLDB $15, V21, V0, V8
	MOVD $cED_z<>+0(SB), R5
	VL (R5), V9
	VCEQB V9, V8, V9
	MOVD $c9F_z<>+0(SB), R5
	VL (R5), V10
	VCHB V0, V10, V10
	VN V10, V9, V9
	VO V9, V20, V20
	MOVD $cF4_z<>+0(SB), R5
	VL (R5), V9
	VCEQB V9, V8, V9
	MOVD $c8F_z<>+0(SB), R5
	VL (R5), V10
	VCHB V0, V10, V10
	VN V10, V9, V9
	VO V9, V20, V20
	VSLDB $15, V22, V1, V9
	VPERM V25, V25, V9, V10
	VCHB V10, V8, V10
	VPERM V26, V26, V9, V11
	VCHB V11, V0, V11
	VN V11, V10, V10
	VO V10, V20, V20
	VLR V0, V21
	VLR V1, V22
	VLR V3, V23
	ADD $16, R2
	ADD $-1, R3
	CMPBNE R3, $0, sloop
	VLGVG $0, V20, R8
	VLGVG $1, V20, R9
	OR R9, R8, R8
	MOVD $1, R10
	CMPBEQ R8, $0, sok
	MOVD $0, R10
sok:
	MOVB R10, ret+32(FP)
	RET

TEXT ·countContVX(SB), NOSPLIT, $0-40
	MOVD src_base+0(FP), R2
	MOVD n+24(FP), R3
	MOVD $cC0_z<>+0(SB), R5
	VL (R5), V25
	MOVD $c80_z<>+0(SB), R5
	VL (R5), V26
	MOVD $c01b_z<>+0(SB), R5
	VL (R5), V27
	VZERO V30
	MOVD $0, R8
csloop:
	VL (R2), V0
	VN V0, V25, V0
	VCEQB V0, V26, V0
	VN V0, V27, V0
	VSUMB V0, V30, V0
	VSUMQF V0, V30, V0
	VLGVG $1, V0, R9
	ADD R9, R8
	ADD $16, R2
	ADD $-1, R3
	CMPBNE R3, $0, csloop
	MOVD R8, ret+32(FP)
	RET

DATA contLen_z<>+0(SB)/1, $0x01
DATA contLen_z<>+1(SB)/1, $0x01
DATA contLen_z<>+2(SB)/1, $0x01
DATA contLen_z<>+3(SB)/1, $0x01
DATA contLen_z<>+4(SB)/1, $0x01
DATA contLen_z<>+5(SB)/1, $0x01
DATA contLen_z<>+6(SB)/1, $0x01
DATA contLen_z<>+7(SB)/1, $0x01
DATA contLen_z<>+8(SB)/1, $0x00
DATA contLen_z<>+9(SB)/1, $0x00
DATA contLen_z<>+10(SB)/1, $0x00
DATA contLen_z<>+11(SB)/1, $0x00
DATA contLen_z<>+12(SB)/1, $0x02
DATA contLen_z<>+13(SB)/1, $0x02
DATA contLen_z<>+14(SB)/1, $0x03
DATA contLen_z<>+15(SB)/1, $0x04
GLOBL contLen_z<>(SB), RODATA|NOPTR, $16

DATA initMins_z<>+0(SB)/1, $0x80
DATA initMins_z<>+1(SB)/1, $0x80
DATA initMins_z<>+2(SB)/1, $0x80
DATA initMins_z<>+3(SB)/1, $0x80
DATA initMins_z<>+4(SB)/1, $0x80
DATA initMins_z<>+5(SB)/1, $0x80
DATA initMins_z<>+6(SB)/1, $0x80
DATA initMins_z<>+7(SB)/1, $0x80
DATA initMins_z<>+8(SB)/1, $0x80
DATA initMins_z<>+9(SB)/1, $0x80
DATA initMins_z<>+10(SB)/1, $0x80
DATA initMins_z<>+11(SB)/1, $0x80
DATA initMins_z<>+12(SB)/1, $0xc2
DATA initMins_z<>+13(SB)/1, $0x80
DATA initMins_z<>+14(SB)/1, $0xe1
DATA initMins_z<>+15(SB)/1, $0xf1
GLOBL initMins_z<>(SB), RODATA|NOPTR, $16

DATA secMins_z<>+0(SB)/1, $0x80
DATA secMins_z<>+1(SB)/1, $0x80
DATA secMins_z<>+2(SB)/1, $0x80
DATA secMins_z<>+3(SB)/1, $0x80
DATA secMins_z<>+4(SB)/1, $0x80
DATA secMins_z<>+5(SB)/1, $0x80
DATA secMins_z<>+6(SB)/1, $0x80
DATA secMins_z<>+7(SB)/1, $0x80
DATA secMins_z<>+8(SB)/1, $0x80
DATA secMins_z<>+9(SB)/1, $0x80
DATA secMins_z<>+10(SB)/1, $0x80
DATA secMins_z<>+11(SB)/1, $0x80
DATA secMins_z<>+12(SB)/1, $0x7f
DATA secMins_z<>+13(SB)/1, $0x7f
DATA secMins_z<>+14(SB)/1, $0xa0
DATA secMins_z<>+15(SB)/1, $0x90
GLOBL secMins_z<>(SB), RODATA|NOPTR, $16

DATA c01_z<>+0(SB)/1, $0x01
DATA c01_z<>+1(SB)/1, $0x01
DATA c01_z<>+2(SB)/1, $0x01
DATA c01_z<>+3(SB)/1, $0x01
DATA c01_z<>+4(SB)/1, $0x01
DATA c01_z<>+5(SB)/1, $0x01
DATA c01_z<>+6(SB)/1, $0x01
DATA c01_z<>+7(SB)/1, $0x01
DATA c01_z<>+8(SB)/1, $0x01
DATA c01_z<>+9(SB)/1, $0x01
DATA c01_z<>+10(SB)/1, $0x01
DATA c01_z<>+11(SB)/1, $0x01
DATA c01_z<>+12(SB)/1, $0x01
DATA c01_z<>+13(SB)/1, $0x01
DATA c01_z<>+14(SB)/1, $0x01
DATA c01_z<>+15(SB)/1, $0x01
GLOBL c01_z<>(SB), RODATA|NOPTR, $16

DATA c02_z<>+0(SB)/1, $0x02
DATA c02_z<>+1(SB)/1, $0x02
DATA c02_z<>+2(SB)/1, $0x02
DATA c02_z<>+3(SB)/1, $0x02
DATA c02_z<>+4(SB)/1, $0x02
DATA c02_z<>+5(SB)/1, $0x02
DATA c02_z<>+6(SB)/1, $0x02
DATA c02_z<>+7(SB)/1, $0x02
DATA c02_z<>+8(SB)/1, $0x02
DATA c02_z<>+9(SB)/1, $0x02
DATA c02_z<>+10(SB)/1, $0x02
DATA c02_z<>+11(SB)/1, $0x02
DATA c02_z<>+12(SB)/1, $0x02
DATA c02_z<>+13(SB)/1, $0x02
DATA c02_z<>+14(SB)/1, $0x02
DATA c02_z<>+15(SB)/1, $0x02
GLOBL c02_z<>(SB), RODATA|NOPTR, $16

DATA cF4_z<>+0(SB)/1, $0xf4
DATA cF4_z<>+1(SB)/1, $0xf4
DATA cF4_z<>+2(SB)/1, $0xf4
DATA cF4_z<>+3(SB)/1, $0xf4
DATA cF4_z<>+4(SB)/1, $0xf4
DATA cF4_z<>+5(SB)/1, $0xf4
DATA cF4_z<>+6(SB)/1, $0xf4
DATA cF4_z<>+7(SB)/1, $0xf4
DATA cF4_z<>+8(SB)/1, $0xf4
DATA cF4_z<>+9(SB)/1, $0xf4
DATA cF4_z<>+10(SB)/1, $0xf4
DATA cF4_z<>+11(SB)/1, $0xf4
DATA cF4_z<>+12(SB)/1, $0xf4
DATA cF4_z<>+13(SB)/1, $0xf4
DATA cF4_z<>+14(SB)/1, $0xf4
DATA cF4_z<>+15(SB)/1, $0xf4
GLOBL cF4_z<>(SB), RODATA|NOPTR, $16

DATA cED_z<>+0(SB)/1, $0xed
DATA cED_z<>+1(SB)/1, $0xed
DATA cED_z<>+2(SB)/1, $0xed
DATA cED_z<>+3(SB)/1, $0xed
DATA cED_z<>+4(SB)/1, $0xed
DATA cED_z<>+5(SB)/1, $0xed
DATA cED_z<>+6(SB)/1, $0xed
DATA cED_z<>+7(SB)/1, $0xed
DATA cED_z<>+8(SB)/1, $0xed
DATA cED_z<>+9(SB)/1, $0xed
DATA cED_z<>+10(SB)/1, $0xed
DATA cED_z<>+11(SB)/1, $0xed
DATA cED_z<>+12(SB)/1, $0xed
DATA cED_z<>+13(SB)/1, $0xed
DATA cED_z<>+14(SB)/1, $0xed
DATA cED_z<>+15(SB)/1, $0xed
GLOBL cED_z<>(SB), RODATA|NOPTR, $16

DATA c9F_z<>+0(SB)/1, $0x9f
DATA c9F_z<>+1(SB)/1, $0x9f
DATA c9F_z<>+2(SB)/1, $0x9f
DATA c9F_z<>+3(SB)/1, $0x9f
DATA c9F_z<>+4(SB)/1, $0x9f
DATA c9F_z<>+5(SB)/1, $0x9f
DATA c9F_z<>+6(SB)/1, $0x9f
DATA c9F_z<>+7(SB)/1, $0x9f
DATA c9F_z<>+8(SB)/1, $0x9f
DATA c9F_z<>+9(SB)/1, $0x9f
DATA c9F_z<>+10(SB)/1, $0x9f
DATA c9F_z<>+11(SB)/1, $0x9f
DATA c9F_z<>+12(SB)/1, $0x9f
DATA c9F_z<>+13(SB)/1, $0x9f
DATA c9F_z<>+14(SB)/1, $0x9f
DATA c9F_z<>+15(SB)/1, $0x9f
GLOBL c9F_z<>(SB), RODATA|NOPTR, $16

DATA c8F_z<>+0(SB)/1, $0x8f
DATA c8F_z<>+1(SB)/1, $0x8f
DATA c8F_z<>+2(SB)/1, $0x8f
DATA c8F_z<>+3(SB)/1, $0x8f
DATA c8F_z<>+4(SB)/1, $0x8f
DATA c8F_z<>+5(SB)/1, $0x8f
DATA c8F_z<>+6(SB)/1, $0x8f
DATA c8F_z<>+7(SB)/1, $0x8f
DATA c8F_z<>+8(SB)/1, $0x8f
DATA c8F_z<>+9(SB)/1, $0x8f
DATA c8F_z<>+10(SB)/1, $0x8f
DATA c8F_z<>+11(SB)/1, $0x8f
DATA c8F_z<>+12(SB)/1, $0x8f
DATA c8F_z<>+13(SB)/1, $0x8f
DATA c8F_z<>+14(SB)/1, $0x8f
DATA c8F_z<>+15(SB)/1, $0x8f
GLOBL c8F_z<>(SB), RODATA|NOPTR, $16

DATA cC0_z<>+0(SB)/1, $0xc0
DATA cC0_z<>+1(SB)/1, $0xc0
DATA cC0_z<>+2(SB)/1, $0xc0
DATA cC0_z<>+3(SB)/1, $0xc0
DATA cC0_z<>+4(SB)/1, $0xc0
DATA cC0_z<>+5(SB)/1, $0xc0
DATA cC0_z<>+6(SB)/1, $0xc0
DATA cC0_z<>+7(SB)/1, $0xc0
DATA cC0_z<>+8(SB)/1, $0xc0
DATA cC0_z<>+9(SB)/1, $0xc0
DATA cC0_z<>+10(SB)/1, $0xc0
DATA cC0_z<>+11(SB)/1, $0xc0
DATA cC0_z<>+12(SB)/1, $0xc0
DATA cC0_z<>+13(SB)/1, $0xc0
DATA cC0_z<>+14(SB)/1, $0xc0
DATA cC0_z<>+15(SB)/1, $0xc0
GLOBL cC0_z<>(SB), RODATA|NOPTR, $16

DATA c80_z<>+0(SB)/1, $0x80
DATA c80_z<>+1(SB)/1, $0x80
DATA c80_z<>+2(SB)/1, $0x80
DATA c80_z<>+3(SB)/1, $0x80
DATA c80_z<>+4(SB)/1, $0x80
DATA c80_z<>+5(SB)/1, $0x80
DATA c80_z<>+6(SB)/1, $0x80
DATA c80_z<>+7(SB)/1, $0x80
DATA c80_z<>+8(SB)/1, $0x80
DATA c80_z<>+9(SB)/1, $0x80
DATA c80_z<>+10(SB)/1, $0x80
DATA c80_z<>+11(SB)/1, $0x80
DATA c80_z<>+12(SB)/1, $0x80
DATA c80_z<>+13(SB)/1, $0x80
DATA c80_z<>+14(SB)/1, $0x80
DATA c80_z<>+15(SB)/1, $0x80
GLOBL c80_z<>(SB), RODATA|NOPTR, $16

DATA c01b_z<>+0(SB)/1, $0x01
DATA c01b_z<>+1(SB)/1, $0x01
DATA c01b_z<>+2(SB)/1, $0x01
DATA c01b_z<>+3(SB)/1, $0x01
DATA c01b_z<>+4(SB)/1, $0x01
DATA c01b_z<>+5(SB)/1, $0x01
DATA c01b_z<>+6(SB)/1, $0x01
DATA c01b_z<>+7(SB)/1, $0x01
DATA c01b_z<>+8(SB)/1, $0x01
DATA c01b_z<>+9(SB)/1, $0x01
DATA c01b_z<>+10(SB)/1, $0x01
DATA c01b_z<>+11(SB)/1, $0x01
DATA c01b_z<>+12(SB)/1, $0x01
DATA c01b_z<>+13(SB)/1, $0x01
DATA c01b_z<>+14(SB)/1, $0x01
DATA c01b_z<>+15(SB)/1, $0x01
GLOBL c01b_z<>(SB), RODATA|NOPTR, $16

