//go:build s390x

package utf8

import (
	"encoding/binary"
	"unicode/utf8"
)

// validBlocksVX runs the Lemire–Keiser SIMD validator over n full 16-byte vector
// blocks of src, returning 1 if those blocks contain no structural UTF-8 error
// within the processed range, 0 otherwise. It does not reject a sequence running
// past the last processed block; the caller re-validates the straddling rune and
// the tail with the scalar path. Generated by go-asmgen (utf8_s390x_gen.go), in
// utf8_s390x.s. The vector facility is baseline on z13+, so there is no runtime
// dispatch. s390x is big-endian; see the generator for lane order.
func validBlocksVX(src []byte, n int) uint8

// countContVX returns the number of UTF-8 continuation bytes ((b & 0xC0) ==
// 0x80) in the first n full 16-byte vector blocks of src. Generated by go-asmgen
// (utf8_s390x_gen.go), in utf8_s390x.s.
func countContVX(src []byte, n int) int64

// asciiPrefixLen returns the number of leading pure-ASCII bytes (b < 0x80) in
// p. Pure-ASCII input is trivially valid UTF-8 with one rune per byte, so any
// consumer of a pure-ASCII prefix can skip the heavy Lemire–Keiser validator
// over that region.
//
// The loop shape mirrors unicode/utf8.Valid: a 4-way-unrolled word scan (32
// bytes / iteration) then a word tail then a byte tail. Each word is loaded
// as a single 8-byte uint64 (not 8 individual byte reads + shifts), so the
// s390x compiler generates one LG per word and one VXE2 loop for the four-
// word OR — measured at memory bandwidth (~23 GB/s on z15). Anything less
// unrolled reaches only ~4-5 GB/s. This ports the asciiBlocksSSE /
// asciiBlocksAVX2 pattern already used by the amd64 kernel.
func asciiPrefixLen(p []byte) int {
	const hiBits = 0x8080808080808080
	orig := len(p)
	// Capacity trim — the stdlib Valid uses this to skip a runtime
	// capacity recompute on each slice op inside the tight loop.
	p = p[:len(p):len(p)]
	for len(p) >= 32 {
		w0 := binary.BigEndian.Uint64(p)
		w1 := binary.BigEndian.Uint64(p[8:])
		w2 := binary.BigEndian.Uint64(p[16:])
		w3 := binary.BigEndian.Uint64(p[24:])
		if (w0|w1|w2|w3)&hiBits != 0 {
			break
		}
		p = p[32:]
	}
	for len(p) >= 8 {
		if binary.BigEndian.Uint64(p)&hiBits != 0 {
			break
		}
		p = p[8:]
	}
	for len(p) > 0 {
		if p[0] >= 0x80 {
			break
		}
		p = p[1:]
	}
	return orig - len(p)
}

// runeStart returns the largest index <= i in p that begins a rune (is not a
// continuation byte), scanning back at most 3 bytes; see utf8_amd64.go.
func runeStart(p []byte, i int) int {
	for j := 0; j < 3 && i > 0 && p[i-1]&0xC0 == 0x80; j++ {
		i--
	}
	if i > 0 {
		i--
	}
	return i
}

// valid validates the bulk of p with the vector kernel over the largest 16-byte
// block-aligned prefix, then re-validates from the last rune boundary before
// that split plus the tail with the standard library.
//
// The pre-scan short-circuits the very common pure-ASCII case: if every byte of
// p is < 0x80, p is trivially valid UTF-8 and no Lemire–Keiser pass is needed
// (measured ~7× speedup on z15 VXE2 vs running the full validator).
func valid(p []byte) bool {
	if asciiPrefixLen(p) == len(p) {
		return true
	}
	n := len(p)
	if n >= 16 {
		blocks := n / 16
		if validBlocksVX(p, blocks) == 0 {
			return false
		}
		return utf8.Valid(p[runeStart(p, blocks*16):])
	}
	return utf8.Valid(p)
}

// countValidPrefix returns RuneCount(p) given that p[:end] is valid UTF-8 and
// cont is the number of continuation bytes in p[:end]; see utf8_amd64.go.
func countValidPrefix(p []byte, end int, cont int64) int {
	split := runeStart(p, end)
	prefixRunes := (end - int(cont)) - 1
	return prefixRunes + utf8.RuneCount(p[split:])
}

// runeCount counts runes in p, byte-identically to unicode/utf8.RuneCount, using
// the vector continuation-byte counter over a SIMD-validated block-aligned
// prefix and the scalar decoder for the straddling rune, the tail, and any
// invalid input; see utf8_amd64.go for the full argument.
//
// The pre-scan short-circuits the very common pure-ASCII case: rune-count of
// a pure-ASCII prefix is just its byte length; only the (possibly-empty) tail
// past the first non-ASCII byte needs the SIMD validator + continuation count.
func runeCount(p []byte) int {
	asciiPfx := asciiPrefixLen(p)
	if asciiPfx == len(p) {
		return len(p)
	}
	// The tail starts at the first non-ASCII byte; that's guaranteed to be a
	// leading byte (top bit = 1), so the SIMD path starts on a rune boundary.
	tail := p[asciiPfx:]
	n := len(tail)
	if n >= 16 {
		blocks := n / 16
		if validBlocksVX(tail, blocks) != 0 {
			return asciiPfx + countValidPrefix(tail, blocks*16, countContVX(tail, blocks))
		}
	}
	return asciiPfx + utf8.RuneCount(tail)
}
