//go:build amd64

package utf8

import (
	"unicode/utf8"

	"golang.org/x/sys/cpu"
)

// validBlocksSSE and validBlocksAVX2 run the Lemire–Keiser SIMD validator over
// n full SIMD blocks of src (16 bytes per block for SSE, 32 for AVX2). Each
// returns 1 if those blocks contain no structural UTF-8 error (bad
// continuation, overlong, surrogate, too-large) within the processed range, 0
// otherwise. They do *not* reject a sequence that runs past the last processed
// block; the caller re-validates that straddling rune and the tail with the
// scalar path. Generated by go-asmgen (utf8_gen.go), in utf8_amd64.s.
func validBlocksSSE(src []byte, n int) uint8
func validBlocksAVX2(src []byte, n int) uint8

var hasAVX2 = cpu.X86.HasAVX2

// runeStart returns the largest index <= i in p that begins a rune (i.e. is not
// a UTF-8 continuation byte), scanning back at most 3 bytes. A rune is at most 4
// bytes, so a boundary always exists within that window unless p[i-3:i] are all
// continuations (a malformed run), in which case we fall back to i so the
// scalar path sees and rejects it.
func runeStart(p []byte, i int) int {
	// Step back over up to 3 continuation bytes; the 4th byte back must be a
	// leading byte (a rune is at most 4 bytes). i is one past the last byte, so
	// p[i-1] is the final byte of the prefix.
	for j := 0; j < 3 && i > 0 && p[i-1]&0xC0 == 0x80; j++ {
		i--
	}
	if i > 0 {
		i-- // p[i] is now the leading byte (or a malformed byte the scalar path rejects)
	}
	return i
}

// valid validates the bulk of p with the widest available SIMD kernel over the
// largest block-aligned prefix, then re-validates from the last rune boundary
// before that split (so a rune straddling the boundary is checked in full) plus
// the tail with the standard library.
func valid(p []byte) bool {
	n := len(p)
	if hasAVX2 && n >= 32 {
		blocks := n / 32
		if validBlocksAVX2(p, blocks) == 0 {
			return false
		}
		return utf8.Valid(p[runeStart(p, blocks*32):])
	}
	if n >= 16 {
		blocks := n / 16
		if validBlocksSSE(p, blocks) == 0 {
			return false
		}
		return utf8.Valid(p[runeStart(p, blocks*16):])
	}
	return utf8.Valid(p)
}
