//go:build amd64

package utf8

import (
	"unicode/utf8"

	"golang.org/x/sys/cpu"
)

// validBlocksSSE and validBlocksAVX2 run the Lemire–Keiser SIMD validator over
// n full SIMD blocks of src (16 bytes per block for SSE, 32 for AVX2). Each
// returns 1 if those blocks contain no structural UTF-8 error (bad
// continuation, overlong, surrogate, too-large) within the processed range, 0
// otherwise. They do *not* reject a sequence that runs past the last processed
// block; the caller re-validates that straddling rune and the tail with the
// scalar path. Generated by go-asmgen (utf8_gen.go), in utf8_amd64.s.
func validBlocksSSE(src []byte, n int) uint8
func validBlocksAVX2(src []byte, n int) uint8

// countContSSE and countContAVX2 return the number of UTF-8 continuation bytes
// (those with (b & 0xC0) == 0x80) in the first n full SIMD blocks of src (16
// bytes per block for SSE, 32 for AVX2). The non-continuation count — i.e. the
// rune count of valid UTF-8 — is n*blockSize minus this. The SSE kernel uses
// POPCNT, so it is gated on cpu.X86.HasPOPCNT; AVX2 CPUs always have POPCNT.
// Generated by go-asmgen (utf8_gen.go), in utf8_amd64.s.
func countContSSE(src []byte, n int) int64
func countContAVX2(src []byte, n int) int64

// asciiBlocksSSE and asciiBlocksAVX2 return the number of leading SIMD blocks of
// src (out of n; 16 bytes per block for SSE, 32 for AVX2) that are pure ASCII
// (every byte < 0x80), stopping at the first block with a high bit. A pure-ASCII
// run costs a load + a high-bit test ([V]PMOVMSKB) per block, so this is the
// memory-bound fast path that keeps all-ASCII input from regressing against the
// stdlib word-at-a-time scan when the heavy Lemire–Keiser validator would
// otherwise touch every byte. Generated by go-asmgen (utf8_gen.go), in
// utf8_amd64.s.
func asciiBlocksSSE(src []byte, n int) int64
func asciiBlocksAVX2(src []byte, n int) int64

var hasAVX2 = cpu.X86.HasAVX2
var hasPOPCNT = cpu.X86.HasPOPCNT

// runeStart returns the largest index <= i in p that begins a rune (i.e. is not
// a UTF-8 continuation byte), scanning back at most 3 bytes. A rune is at most 4
// bytes, so a boundary always exists within that window unless p[i-3:i] are all
// continuations (a malformed run), in which case we fall back to i so the
// scalar path sees and rejects it.
func runeStart(p []byte, i int) int {
	// Step back over up to 3 continuation bytes; the 4th byte back must be a
	// leading byte (a rune is at most 4 bytes). i is one past the last byte, so
	// p[i-1] is the final byte of the prefix.
	for j := 0; j < 3 && i > 0 && p[i-1]&0xC0 == 0x80; j++ {
		i--
	}
	if i > 0 {
		i-- // p[i] is now the leading byte (or a malformed byte the scalar path rejects)
	}
	return i
}

// valid validates the bulk of p with the widest available SIMD kernel over the
// largest block-aligned prefix, then re-validates from the last rune boundary
// before that split (so a rune straddling the boundary is checked in full) plus
// the tail with the standard library.
func valid(p []byte) bool {
	n := len(p)
	if hasAVX2 && n >= 32 {
		blocks := n / 32
		// Cheap ASCII pre-scan: pure-ASCII bytes are trivially valid, so if the
		// whole block-aligned region is ASCII only the sub-32 tail remains. This
		// keeps the (very common) all-ASCII case at memory bandwidth instead of
		// paying the full Lemire–Keiser validation cost.
		if int(asciiBlocksAVX2(p, blocks)) == blocks {
			return utf8.Valid(p[blocks*32:])
		}
		if validBlocksAVX2(p, blocks) == 0 {
			return false
		}
		return utf8.Valid(p[runeStart(p, blocks*32):])
	}
	if n >= 16 {
		blocks := n / 16
		if int(asciiBlocksSSE(p, blocks)) == blocks {
			return utf8.Valid(p[blocks*16:])
		}
		if validBlocksSSE(p, blocks) == 0 {
			return false
		}
		return utf8.Valid(p[runeStart(p, blocks*16):])
	}
	return utf8.Valid(p)
}

// runeCount counts the runes in p, byte-identically to unicode/utf8.RuneCount.
//
// In valid UTF-8 the rune count equals the number of non-continuation bytes
// (bytes with (b & 0xC0) != 0x80): every encoded rune has exactly one leading
// (non-continuation) byte. That identity breaks on invalid input — the stdlib
// decoder counts each byte of a malformed sequence as its own 1-byte rune — so
// the SIMD fast path is only trusted over a block-aligned prefix the validator
// confirms is valid UTF-8 ending on a rune boundary. The straddling rune and
// the tail go to the scalar decoder; if the prefix is invalid we fall back to
// the scalar decoder for the whole input. Counting is therefore exact for all
// input, including invalid and truncated sequences.
func runeCount(p []byte) int {
	n := len(p)
	if hasAVX2 && n >= 32 {
		blocks := n / 32
		// Cheap ASCII pre-scan: a pure-ASCII prefix has one rune per byte, so if
		// the whole block-aligned region is ASCII the count is blocks*32 plus the
		// scalar count of the sub-32 tail — no heavy validator pass needed.
		if int(asciiBlocksAVX2(p, blocks)) == blocks {
			return blocks*32 + utf8.RuneCount(p[blocks*32:])
		}
		if c := validBlocksAVX2(p, blocks); c != 0 {
			return countValidPrefix(p, blocks*32, countContAVX2(p, blocks))
		}
		return utf8.RuneCount(p)
	}
	if hasPOPCNT && n >= 16 {
		blocks := n / 16
		if int(asciiBlocksSSE(p, blocks)) == blocks {
			return blocks*16 + utf8.RuneCount(p[blocks*16:])
		}
		if c := validBlocksSSE(p, blocks); c != 0 {
			return countValidPrefix(p, blocks*16, countContSSE(p, blocks))
		}
		return utf8.RuneCount(p)
	}
	return utf8.RuneCount(p)
}

// countValidPrefix returns RuneCount(p) given that p[:end] is valid UTF-8 and
// cont is the number of continuation bytes in p[:end]. It splits at the rune
// boundary at or before end (runeStart) so the straddling rune is decoded once,
// by the scalar tail, and never double-counted.
//
// The runes wholly inside p[:split] number nonCont(p[:split]). Because p[:end]
// is valid, p[split] is the leading byte of the rune straddling end and
// p[split+1:end] are its continuation bytes; hence nonCont(p[:end]) =
// nonCont(p[:split]) + 1, i.e. nonCont(p[:split]) = (end - cont) - 1. Adding
// the scalar RuneCount of p[split:] (which re-counts that straddling rune and
// the tail) gives the exact total. When split == end (the block ends exactly on
// a boundary) there is no straddling rune; runeStart still steps back to the
// last leading byte, so the same arithmetic holds and the scalar tail re-counts
// that final rune.
func countValidPrefix(p []byte, end int, cont int64) int {
	split := runeStart(p, end)
	prefixRunes := (end - int(cont)) - 1
	return prefixRunes + utf8.RuneCount(p[split:])
}
