// Code generated by go-asmgen. DO NOT EDIT.

//go:build ppc64le

#include "textflag.h"

TEXT ·validBlocksVSX(SB), NOSPLIT, $0-33
	MOVD src_base+0(FP), R4
	MOVD n+24(FP), R5
	MOVD $contLen_p<>+0(SB), R6
	LXVB16X (R0)(R6), VS56
	MOVD $initMins_p<>+0(SB), R6
	LXVB16X (R0)(R6), VS57
	MOVD $secMins_p<>+0(SB), R6
	LXVB16X (R0)(R6), VS58
	MOVD $c04_p<>+0(SB), R6
	LXVB16X (R0)(R6), VS59
	MOVD $c01_p<>+0(SB), R6
	LXVB16X (R0)(R6), VS60
	MOVD $c02_p<>+0(SB), R6
	LXVB16X (R0)(R6), VS61
	MOVD $cF4_p<>+0(SB), R6
	LXVB16X (R0)(R6), VS62
	MOVD $c00_p<>+0(SB), R6
	LXVB16X (R0)(R6), VS63
	VXOR V20, V20, V20
	VXOR V21, V21, V21
	VXOR V22, V22, V22
	VXOR V23, V23, V23
	MOVD $0, R7
sloop:
	LXVB16X (R7)(R4), VS32
	VSRB V0, V27, V1
	VSUBUBS V0, V30, V3
	VOR V3, V20, V20
	VPERM V24, V24, V1, V2
	VSLDOI $15, V23, V2, V3
	VSUBUBS V3, V28, V3
	VADDUBM V2, V3, V3
	VSLDOI $14, V23, V3, V5
	VSUBUBS V5, V29, V5
	VADDUBM V5, V3, V3
	VCMPGTSB V3, V2, V5
	VCMPGTSB V2, V31, V6
	VCMPEQUB V6, V5, V5
	VOR V5, V20, V20
	VSLDOI $15, V21, V0, V8
	MOVD $cED_p<>+0(SB), R6
	LXVB16X (R0)(R6), VS41
	VCMPEQUB V9, V8, V9
	MOVD $c9F_p<>+0(SB), R6
	LXVB16X (R0)(R6), VS42
	VCMPGTSB V0, V10, V10
	VAND V10, V9, V9
	VOR V9, V20, V20
	MOVD $cF4_p<>+0(SB), R6
	LXVB16X (R0)(R6), VS41
	VCMPEQUB V9, V8, V9
	MOVD $c8F_p<>+0(SB), R6
	LXVB16X (R0)(R6), VS42
	VCMPGTSB V0, V10, V10
	VAND V10, V9, V9
	VOR V9, V20, V20
	VSLDOI $15, V22, V1, V9
	VPERM V25, V25, V9, V10
	VCMPGTSB V10, V8, V10
	VPERM V26, V26, V9, V11
	VCMPGTSB V11, V0, V11
	VAND V11, V10, V10
	VOR V10, V20, V20
	VOR V0, V0, V21
	VOR V1, V1, V22
	VOR V3, V3, V23
	ADD $16, R7
	ADD $-1, R5
	CMP R5, $0
	BNE sloop
	MFVSRD VS52, R8
	VSLDOI $8, V20, V20, V4
	MFVSRD VS36, R9
	OR R9, R8, R8
	MOVD $1, R10
	CMP R8, $0
	BEQ sok
	MOVD $0, R10
sok:
	MOVB R10, ret+32(FP)
	RET

TEXT ·countContVSX(SB), NOSPLIT, $0-40
	MOVD src_base+0(FP), R4
	MOVD n+24(FP), R5
	MOVD $cC0_p<>+0(SB), R6
	LXVB16X (R0)(R6), VS57
	MOVD $c80_p<>+0(SB), R6
	LXVB16X (R0)(R6), VS58
	MOVD $c01b_p<>+0(SB), R6
	LXVB16X (R0)(R6), VS59
	MOVD $0, R8
	MOVD $0, R7
csloop:
	LXVB16X (R7)(R4), VS32
	VAND V0, V25, V0
	VCMPEQUB V0, V26, V0
	VAND V0, V27, V0
	VPOPCNTD V0, V0
	MFVSRD VS32, R9
	ADD R9, R8
	VSLDOI $8, V0, V0, V1
	MFVSRD VS33, R9
	ADD R9, R8
	ADD $16, R7
	ADD $-1, R5
	CMP R5, $0
	BNE csloop
	MOVD R8, ret+32(FP)
	RET

DATA contLen_p<>+0(SB)/1, $0x01
DATA contLen_p<>+1(SB)/1, $0x01
DATA contLen_p<>+2(SB)/1, $0x01
DATA contLen_p<>+3(SB)/1, $0x01
DATA contLen_p<>+4(SB)/1, $0x01
DATA contLen_p<>+5(SB)/1, $0x01
DATA contLen_p<>+6(SB)/1, $0x01
DATA contLen_p<>+7(SB)/1, $0x01
DATA contLen_p<>+8(SB)/1, $0x00
DATA contLen_p<>+9(SB)/1, $0x00
DATA contLen_p<>+10(SB)/1, $0x00
DATA contLen_p<>+11(SB)/1, $0x00
DATA contLen_p<>+12(SB)/1, $0x02
DATA contLen_p<>+13(SB)/1, $0x02
DATA contLen_p<>+14(SB)/1, $0x03
DATA contLen_p<>+15(SB)/1, $0x04
GLOBL contLen_p<>(SB), RODATA|NOPTR, $16

DATA initMins_p<>+0(SB)/1, $0x80
DATA initMins_p<>+1(SB)/1, $0x80
DATA initMins_p<>+2(SB)/1, $0x80
DATA initMins_p<>+3(SB)/1, $0x80
DATA initMins_p<>+4(SB)/1, $0x80
DATA initMins_p<>+5(SB)/1, $0x80
DATA initMins_p<>+6(SB)/1, $0x80
DATA initMins_p<>+7(SB)/1, $0x80
DATA initMins_p<>+8(SB)/1, $0x80
DATA initMins_p<>+9(SB)/1, $0x80
DATA initMins_p<>+10(SB)/1, $0x80
DATA initMins_p<>+11(SB)/1, $0x80
DATA initMins_p<>+12(SB)/1, $0xc2
DATA initMins_p<>+13(SB)/1, $0x80
DATA initMins_p<>+14(SB)/1, $0xe1
DATA initMins_p<>+15(SB)/1, $0xf1
GLOBL initMins_p<>(SB), RODATA|NOPTR, $16

DATA secMins_p<>+0(SB)/1, $0x80
DATA secMins_p<>+1(SB)/1, $0x80
DATA secMins_p<>+2(SB)/1, $0x80
DATA secMins_p<>+3(SB)/1, $0x80
DATA secMins_p<>+4(SB)/1, $0x80
DATA secMins_p<>+5(SB)/1, $0x80
DATA secMins_p<>+6(SB)/1, $0x80
DATA secMins_p<>+7(SB)/1, $0x80
DATA secMins_p<>+8(SB)/1, $0x80
DATA secMins_p<>+9(SB)/1, $0x80
DATA secMins_p<>+10(SB)/1, $0x80
DATA secMins_p<>+11(SB)/1, $0x80
DATA secMins_p<>+12(SB)/1, $0x7f
DATA secMins_p<>+13(SB)/1, $0x7f
DATA secMins_p<>+14(SB)/1, $0xa0
DATA secMins_p<>+15(SB)/1, $0x90
GLOBL secMins_p<>(SB), RODATA|NOPTR, $16

DATA c04_p<>+0(SB)/1, $0x04
DATA c04_p<>+1(SB)/1, $0x04
DATA c04_p<>+2(SB)/1, $0x04
DATA c04_p<>+3(SB)/1, $0x04
DATA c04_p<>+4(SB)/1, $0x04
DATA c04_p<>+5(SB)/1, $0x04
DATA c04_p<>+6(SB)/1, $0x04
DATA c04_p<>+7(SB)/1, $0x04
DATA c04_p<>+8(SB)/1, $0x04
DATA c04_p<>+9(SB)/1, $0x04
DATA c04_p<>+10(SB)/1, $0x04
DATA c04_p<>+11(SB)/1, $0x04
DATA c04_p<>+12(SB)/1, $0x04
DATA c04_p<>+13(SB)/1, $0x04
DATA c04_p<>+14(SB)/1, $0x04
DATA c04_p<>+15(SB)/1, $0x04
GLOBL c04_p<>(SB), RODATA|NOPTR, $16

DATA c01_p<>+0(SB)/1, $0x01
DATA c01_p<>+1(SB)/1, $0x01
DATA c01_p<>+2(SB)/1, $0x01
DATA c01_p<>+3(SB)/1, $0x01
DATA c01_p<>+4(SB)/1, $0x01
DATA c01_p<>+5(SB)/1, $0x01
DATA c01_p<>+6(SB)/1, $0x01
DATA c01_p<>+7(SB)/1, $0x01
DATA c01_p<>+8(SB)/1, $0x01
DATA c01_p<>+9(SB)/1, $0x01
DATA c01_p<>+10(SB)/1, $0x01
DATA c01_p<>+11(SB)/1, $0x01
DATA c01_p<>+12(SB)/1, $0x01
DATA c01_p<>+13(SB)/1, $0x01
DATA c01_p<>+14(SB)/1, $0x01
DATA c01_p<>+15(SB)/1, $0x01
GLOBL c01_p<>(SB), RODATA|NOPTR, $16

DATA c02_p<>+0(SB)/1, $0x02
DATA c02_p<>+1(SB)/1, $0x02
DATA c02_p<>+2(SB)/1, $0x02
DATA c02_p<>+3(SB)/1, $0x02
DATA c02_p<>+4(SB)/1, $0x02
DATA c02_p<>+5(SB)/1, $0x02
DATA c02_p<>+6(SB)/1, $0x02
DATA c02_p<>+7(SB)/1, $0x02
DATA c02_p<>+8(SB)/1, $0x02
DATA c02_p<>+9(SB)/1, $0x02
DATA c02_p<>+10(SB)/1, $0x02
DATA c02_p<>+11(SB)/1, $0x02
DATA c02_p<>+12(SB)/1, $0x02
DATA c02_p<>+13(SB)/1, $0x02
DATA c02_p<>+14(SB)/1, $0x02
DATA c02_p<>+15(SB)/1, $0x02
GLOBL c02_p<>(SB), RODATA|NOPTR, $16

DATA cF4_p<>+0(SB)/1, $0xf4
DATA cF4_p<>+1(SB)/1, $0xf4
DATA cF4_p<>+2(SB)/1, $0xf4
DATA cF4_p<>+3(SB)/1, $0xf4
DATA cF4_p<>+4(SB)/1, $0xf4
DATA cF4_p<>+5(SB)/1, $0xf4
DATA cF4_p<>+6(SB)/1, $0xf4
DATA cF4_p<>+7(SB)/1, $0xf4
DATA cF4_p<>+8(SB)/1, $0xf4
DATA cF4_p<>+9(SB)/1, $0xf4
DATA cF4_p<>+10(SB)/1, $0xf4
DATA cF4_p<>+11(SB)/1, $0xf4
DATA cF4_p<>+12(SB)/1, $0xf4
DATA cF4_p<>+13(SB)/1, $0xf4
DATA cF4_p<>+14(SB)/1, $0xf4
DATA cF4_p<>+15(SB)/1, $0xf4
GLOBL cF4_p<>(SB), RODATA|NOPTR, $16

DATA cED_p<>+0(SB)/1, $0xed
DATA cED_p<>+1(SB)/1, $0xed
DATA cED_p<>+2(SB)/1, $0xed
DATA cED_p<>+3(SB)/1, $0xed
DATA cED_p<>+4(SB)/1, $0xed
DATA cED_p<>+5(SB)/1, $0xed
DATA cED_p<>+6(SB)/1, $0xed
DATA cED_p<>+7(SB)/1, $0xed
DATA cED_p<>+8(SB)/1, $0xed
DATA cED_p<>+9(SB)/1, $0xed
DATA cED_p<>+10(SB)/1, $0xed
DATA cED_p<>+11(SB)/1, $0xed
DATA cED_p<>+12(SB)/1, $0xed
DATA cED_p<>+13(SB)/1, $0xed
DATA cED_p<>+14(SB)/1, $0xed
DATA cED_p<>+15(SB)/1, $0xed
GLOBL cED_p<>(SB), RODATA|NOPTR, $16

DATA c9F_p<>+0(SB)/1, $0x9f
DATA c9F_p<>+1(SB)/1, $0x9f
DATA c9F_p<>+2(SB)/1, $0x9f
DATA c9F_p<>+3(SB)/1, $0x9f
DATA c9F_p<>+4(SB)/1, $0x9f
DATA c9F_p<>+5(SB)/1, $0x9f
DATA c9F_p<>+6(SB)/1, $0x9f
DATA c9F_p<>+7(SB)/1, $0x9f
DATA c9F_p<>+8(SB)/1, $0x9f
DATA c9F_p<>+9(SB)/1, $0x9f
DATA c9F_p<>+10(SB)/1, $0x9f
DATA c9F_p<>+11(SB)/1, $0x9f
DATA c9F_p<>+12(SB)/1, $0x9f
DATA c9F_p<>+13(SB)/1, $0x9f
DATA c9F_p<>+14(SB)/1, $0x9f
DATA c9F_p<>+15(SB)/1, $0x9f
GLOBL c9F_p<>(SB), RODATA|NOPTR, $16

DATA c8F_p<>+0(SB)/1, $0x8f
DATA c8F_p<>+1(SB)/1, $0x8f
DATA c8F_p<>+2(SB)/1, $0x8f
DATA c8F_p<>+3(SB)/1, $0x8f
DATA c8F_p<>+4(SB)/1, $0x8f
DATA c8F_p<>+5(SB)/1, $0x8f
DATA c8F_p<>+6(SB)/1, $0x8f
DATA c8F_p<>+7(SB)/1, $0x8f
DATA c8F_p<>+8(SB)/1, $0x8f
DATA c8F_p<>+9(SB)/1, $0x8f
DATA c8F_p<>+10(SB)/1, $0x8f
DATA c8F_p<>+11(SB)/1, $0x8f
DATA c8F_p<>+12(SB)/1, $0x8f
DATA c8F_p<>+13(SB)/1, $0x8f
DATA c8F_p<>+14(SB)/1, $0x8f
DATA c8F_p<>+15(SB)/1, $0x8f
GLOBL c8F_p<>(SB), RODATA|NOPTR, $16

DATA c00_p<>+0(SB)/1, $0x00
DATA c00_p<>+1(SB)/1, $0x00
DATA c00_p<>+2(SB)/1, $0x00
DATA c00_p<>+3(SB)/1, $0x00
DATA c00_p<>+4(SB)/1, $0x00
DATA c00_p<>+5(SB)/1, $0x00
DATA c00_p<>+6(SB)/1, $0x00
DATA c00_p<>+7(SB)/1, $0x00
DATA c00_p<>+8(SB)/1, $0x00
DATA c00_p<>+9(SB)/1, $0x00
DATA c00_p<>+10(SB)/1, $0x00
DATA c00_p<>+11(SB)/1, $0x00
DATA c00_p<>+12(SB)/1, $0x00
DATA c00_p<>+13(SB)/1, $0x00
DATA c00_p<>+14(SB)/1, $0x00
DATA c00_p<>+15(SB)/1, $0x00
GLOBL c00_p<>(SB), RODATA|NOPTR, $16

DATA cC0_p<>+0(SB)/1, $0xc0
DATA cC0_p<>+1(SB)/1, $0xc0
DATA cC0_p<>+2(SB)/1, $0xc0
DATA cC0_p<>+3(SB)/1, $0xc0
DATA cC0_p<>+4(SB)/1, $0xc0
DATA cC0_p<>+5(SB)/1, $0xc0
DATA cC0_p<>+6(SB)/1, $0xc0
DATA cC0_p<>+7(SB)/1, $0xc0
DATA cC0_p<>+8(SB)/1, $0xc0
DATA cC0_p<>+9(SB)/1, $0xc0
DATA cC0_p<>+10(SB)/1, $0xc0
DATA cC0_p<>+11(SB)/1, $0xc0
DATA cC0_p<>+12(SB)/1, $0xc0
DATA cC0_p<>+13(SB)/1, $0xc0
DATA cC0_p<>+14(SB)/1, $0xc0
DATA cC0_p<>+15(SB)/1, $0xc0
GLOBL cC0_p<>(SB), RODATA|NOPTR, $16

DATA c80_p<>+0(SB)/1, $0x80
DATA c80_p<>+1(SB)/1, $0x80
DATA c80_p<>+2(SB)/1, $0x80
DATA c80_p<>+3(SB)/1, $0x80
DATA c80_p<>+4(SB)/1, $0x80
DATA c80_p<>+5(SB)/1, $0x80
DATA c80_p<>+6(SB)/1, $0x80
DATA c80_p<>+7(SB)/1, $0x80
DATA c80_p<>+8(SB)/1, $0x80
DATA c80_p<>+9(SB)/1, $0x80
DATA c80_p<>+10(SB)/1, $0x80
DATA c80_p<>+11(SB)/1, $0x80
DATA c80_p<>+12(SB)/1, $0x80
DATA c80_p<>+13(SB)/1, $0x80
DATA c80_p<>+14(SB)/1, $0x80
DATA c80_p<>+15(SB)/1, $0x80
GLOBL c80_p<>(SB), RODATA|NOPTR, $16

DATA c01b_p<>+0(SB)/1, $0x01
DATA c01b_p<>+1(SB)/1, $0x01
DATA c01b_p<>+2(SB)/1, $0x01
DATA c01b_p<>+3(SB)/1, $0x01
DATA c01b_p<>+4(SB)/1, $0x01
DATA c01b_p<>+5(SB)/1, $0x01
DATA c01b_p<>+6(SB)/1, $0x01
DATA c01b_p<>+7(SB)/1, $0x01
DATA c01b_p<>+8(SB)/1, $0x01
DATA c01b_p<>+9(SB)/1, $0x01
DATA c01b_p<>+10(SB)/1, $0x01
DATA c01b_p<>+11(SB)/1, $0x01
DATA c01b_p<>+12(SB)/1, $0x01
DATA c01b_p<>+13(SB)/1, $0x01
DATA c01b_p<>+14(SB)/1, $0x01
DATA c01b_p<>+15(SB)/1, $0x01
GLOBL c01b_p<>(SB), RODATA|NOPTR, $16

